### ISSUE TITLE
WoodEC5 law

### ISSUE THREAD

**Issue by LGCajot** [gmsafir/gmsafir#1]
The WoodEc5 law seems not working. Gmsafir enables to create file *.in; However the run Safir fails (lack of convergence).
Louis-Guy

**Comment by JMFranssen** [comment]
Thanks Louis-Guy, but this issue (that has been solved) has nothing to do with GmSAFIR. This kind of comment is better sent via e-mail to safir@uliege.be

**Comment by LGCajot** [comment]
Thanks for the quick answer and the quick analyze of my issue.
