### ISSUE TITLE
Problem when assigning two uniformly distributed loads to the same curve

### ISSUE THREAD

**Issue by Rosario26** [gmsafir/gmsafir#100]
Dears,

I have a simple 3D steel frame, 2 columns and 1 beam. No load is applied on columns. The beam is loaded with two different uniformly distributed loads: one coming from the physical group (dead weight) and the other directly assigned on the curve.
As a result, I expect that the beam is loaded with the sum of the two uniformly distributed loads.

Instead, the created .in file reveals some errors in the elements being loaded, with part of the loads incorrectly assigned to one column.

I attach all the relevant files and some screenshots to immediately see what I'm detecting. I also attach you two alternatives of that part of the .in file I expected instead, alternatively using one or two NLOAD.

So, can you help me in understanding why the loads are misassigned when passing from the model in gmsafir to the .in output file?

Many thanks, 
Rosario

<img width="450" alt="3d frame loads diamond" src="https://github.com/gmsafir/gmsafir/assets/158551610/87d2b3be-8136-453b-8de9-bdfa7c9831ae">
<img width="508" alt="3d frame loads gmsafir" src="https://github.com/gmsafir/gmsafir/assets/158551610/7feb457c-5377-4984-ab49-76a39b4b2dad">
<img width="243" alt="expected loads in file" src="https://github.com/gmsafir/gmsafir/assets/158551610/6867c313-7c89-4f22-bd7d-ff019154f017">
<img width="243" alt="expected loads in file_nload2" src="https://github.com/gmsafir/gmsafir/assets/158551610/fdaa3cf9-733f-4ff8-8e22-28a2cc144711">
<img width="243" alt="loads in file" src="https://github.com/gmsafir/gmsafir/assets/158551610/b3cfd37a-7a73-46ae-8d7d-a50b641065c2">
[load test.zip](https://github.com/gmsafir/gmsafir/files/15310232/load.test.zip)

**Comment by Rosario26** [comment]
For completeness, I attach you an image with the element numbering.
<img width="457" alt="3d frame loads diamond element numbering" src="https://github.com/gmsafir/gmsafir/assets/158551610/cce5750b-1b78-483b-93e1-77b41daa4bc0">

**Comment by gmsafir** [comment]
let us start with GmSAFIR generating the .IN file, we will see later with DIAMOND.
The content of the loads that you defined are provided in your G4S file (and you can view it in GmSAFIR with the menu "VIEW/View loads":
- you assigned FLOAD with pressures (0,0,-2000) to Curve 2 (the beam);
- you assigned FLOAD with load function y.fct to Physical Curve 5 (the 2 columns) and to Physical Curve 6 (the beam)
So the IN file reflects correctly these elements.
