### ISSUE TITLE
GmSAFIR Modelling Query 

### ISSUE THREAD

**Issue by farialtanjim** [gmsafir/gmsafir#101]
Hi There, 

We are doing modelling in GmSAFIR and I was hoping you can assist. 
 
We have modelled a 370 thick slab with reinforcement and insulation in a .TSH file. When we link the .TSH file to a GmSAFIR structural model I am receiving an error shown below that the rebar material is not assigned correctly  and the list index is out of range. 
 
Error: Material steelec2mrecovered from your .TSH files is not assigned correctly in the current structural cast: list index out of range. 

Kind Regards, 
Farial Tanjim

[ModelMessage.pdf](https://github.com/user-attachments/files/16103196/ModelMessage.pdf)

**Comment by gmsafir** [comment]
Please upload your .geo and .g4s files here, after renaming them as .geo.txt and .g4s.txt for correct upload.
This is needed for diagnostic on my side

**Comment by farialtanjim** [comment]
Hi There, 

Model uploaded as follows: 
Structural Frame Models
[FRAME.g4s.txt](https://github.com/user-attachments/files/16118898/FRAME.g4s.txt)
[FRAME.geo.txt](https://github.com/user-attachments/files/16118899/FRAME.geo.txt)

Beam Models
[610UB101P.g4s.txt](https://github.com/user-attachments/files/16118907/610UB101P.g4s.txt)
[610UB101P.geo.txt](https://github.com/user-attachments/files/16118908/610UB101P.geo.txt)

Slab Models
[SLABP.g4s.txt](https://github.com/user-attachments/files/16118910/SLABP.g4s.txt)
[SLABP.geo.txt](https://github.com/user-attachments/files/16118911/SLABP.geo.txt)


Thank you 
Farial Tanjim

**Comment by farialtanjim** [comment]
Hi There, 

Just checking in on our earlier query. If you could please provide some comments. 

Kind Regards, 

Farial Tanjim

**Comment by gmsafir** [comment]
There was a bug in the code concerning the allocation of shell rebar materials.
Uploading newest version will solve your problem.

**Comment by farialtanjim** [comment]
Thank you very much. We knew there was an issue. 

Would you be able me a link to the latest update of Safir, just to make sure. 

Thanks again for the clarification. 

Kind Regards, 

Farial Tanjim

**Comment by gmsafir** [comment]
You are at the correct place to retrieve the latest GmSAFIR, not the latest SAFIR: https://github.com/gmsafir/gmsafir

**Comment by Altorcas** [comment]
Good evening,

When I dowload this new version and I create the .IN file I get the following message: 

![image](https://github.com/gmsafir/gmsafir/assets/135019498/2595c656-f4d6-4451-aeab-db9e48ed5555)

In the .IN file my rebar material is the second one: 

![image](https://github.com/gmsafir/gmsafir/assets/135019498/80af4396-edda-40f0-94f4-5ee2f8250bcd)

But the rebar material assigned in the REBARMAT command is number 1 (which is SILCOETC2D: this material is not a uniaxial stress model).

I can manually type that the material for the REBARMAT is 2, althought I did not have to do that in the previous version.

Thank you!

**Comment by gmsafir** [comment]
please share your sample .geo and .g4s for debug

**Comment by Altorcas** [comment]
Hello, 
[M0geo.txt](https://github.com/user-attachments/files/16191550/M0geo.txt)

[M0g4s.txt](https://github.com/user-attachments/files/16191549/M0g4s.txt)

Here you have both files. Thank you!

**Comment by gmsafir** [comment]
there was a bug in the rebar material writing in .IN file. Upload newest code version for correction.
