### ISSUE TITLE
error when viewing materials or creating input file

### ISSUE THREAD

**Issue by piri17** [gmsafir/gmsafir#103]
I've created a model on gmsafir but whenever I click view material or create input file, I keep getting an error which says: 'problem in collecting obliqdispl;0 property attributes: list index out of range'.  How do I resolve this issue?

**Comment by piri17** [comment]
I've managed to create the input file however, I can't add files on safir shell. How do i resolve this?

**Comment by gmsafir** [comment]
do you still need help in GmSAFIR or is your problem solved?

**Comment by piri17** [comment]
I've managed to resolve the issue with GmSAFIR. But I'm having problems adding the input file on shell. The file section still remains blank, even after adding the input file. Are you able to help with this issue or do you know who I can contact to help resolve the issue with shell.

**Comment by gmsafir** [comment]
Can you explicit " I'm having problems adding the input file on shell. The file section still remains blank, even after adding the input file". Which file section? Add the input file to what?

**Comment by piri17** [comment]
I'm unable to add the input file on Safir shell. Whenever I add the input file from what I created on GmSafir or even from the examples I obtained from your website onto Safir Shell, the screen remains blank under file name where it is meant to appear. However, the 'run' and 'delete' options are abled indicating the file should be appearing but it isn't. I've put in the location of the safir executable file in 'safir path' correctly and I'm unsure what else I could do differently. I've attached a screenshot below. 

![Uploading Clipboard 2024-08-12 12-31-48.jpg…]()

**Comment by gmsafir** [comment]
please, upload here your input file, so as to make a test

**Comment by gmsafir** [comment]
and provide also the .geo/.g4s files that you used to successfully creat ethe input file

**Comment by piri17** [comment]
I've attatched the files
________________________________

**Comment by gmsafir** [comment]
upload did not work.
To upload each of the 3 files: change extensions before upload: .geo => .geo.txt / .g4s => .g4s.txt / .IN => .IN.txt

**Comment by piri17** [comment]
Ive uploaded the files as .txt.
________________________________

**Comment by gmsafir** [comment]
ok, there is no problem in getting a correct .IN with GmSAFIR through your 2 files .geo and .g4s. I write an email to SAFIR@uliege.be to continue the discussion

**Comment by piri17** [comment]
Thank you so much
________________________________
