### ISSUE TITLE
Is it possible to specify SYMVOID in GmSafir?

### ISSUE THREAD

**Issue by JSoini** [gmsafir/gmsafir#106]
I would like to perform a 2D thermal analysis for a wall with a void (an air gap between surfaces). This is essentially a one-dimensional problem, so I would like to use the SYMVOID command for both sides of the cross-section. However, I haven't found a way to specify the SYMVOID command in GmSafir. Is this possible? If it is possible, could you inform me how to do it?

Another option is to model dummy plates (e.g. thin steel plate), which would act as mirrors (by using emissivity 1,0).

While I can add the SYMVOID command after generating the IN file, it would streamline the workflow if it were possible to specify it directly in GmSafir.

![options_to_model_continuous_void](https://github.com/user-attachments/assets/0d2daff9-4664-42a0-b79c-108b6aa6a342)

![symvoid_gmsafir](https://github.com/user-attachments/assets/09131f2d-f700-4f2b-bef0-c1cbc7d47bb3)

**Comment by JSoini** [comment]
Thanks a lot for the quick reply! I hadn't noticed that this possibility is only available for the "Curve" entity and not for the "Physical Curve" entity, which I was looking at. I assume that the reason is that the symmetry axis is always a single line, while a Physical Curve can consist of a set of lines that are not parallel. Therefore, it makes sense that symmetry commands should only be applicable to "Curve" entities.

**Comment by Sapiens333** [comment]
Hi. Apologies for reopening this issue. Would you be able to provide a more detailed explanation of the steps required to define a SYMVOID constraint?

Here’s what I have attempted so far:
1. I tried defining a Curve entity as a simple line (following section 5.2.2 Curves in the manual).
2. As I understand, the Curve does not need to be assigned to a Physical Curve (i.e., it should not have a physical tag).
3. After double-clicking on the line, I expected the Void SymAxis Constraint option to appear, but I may have missed a step.
Please see the attached image for reference:

![Image](https://github.com/user-attachments/assets/36a21f8d-23e1-4f1e-a78e-193c453f85d2)

If you could guide me through the correct steps, it would be greatly appreciated. Thank you!
