### ISSUE TITLE
ZZ0 shell incorrect format

### ISSUE THREAD

**Issue by tgernay** [gmsafir/gmsafir#11]
Hi, in structural 3D model with shell FE, in 'Property Type' SHELL MATERIAL, GmSAFIR allows inputting the NODEL LEVEL Z0 for the shells.
GmSAFIR currently writes it in the .IN file with the line 
    ZZERO value
but SAFIR requires
    Z0 value
the input file does not run with ZZERO but runs after changing to Z0

**Comment by gmsafir** [comment]
It shall now be correct in the new version
