### ISSUE TITLE
mesh error

### ISSUE THREAD

**Issue by MPSimu** [gmsafir/gmsafir#14]
I imported step file for thermal simulation. While generating 3d mesh I am facing two problems 1) elements distortion, Jacobian is negative 2)  Nodes of 2 solids are not coincident. See the attached images.
![mesh](https://user-images.githubusercontent.com/102736879/168542574-af6e774e-1122-4aae-ac39-ab7a32b50428.jpg)

![error](https://user-images.githubusercontent.com/102736879/168542654-0d78e8a5-d8ab-4c57-a9ac-187564c4f647.jpg)

**Comment by MPSimu** [comment]
what steps should I take to get good and error free input file

**Comment by gmsafir** [comment]
Upload your .geo and .g4s please (if not possible in this open forum, send it to me privately).

**Comment by MPSimu** [comment]
Hello, enclosed are the files. Thanks

Von: gmsafir ***@***.***>
Gesendet: Montag, 16. Mai 2022 09:52
An: gmsafir/gmsafir ***@***.***>
Cc: Mayur Patil ***@***.***>; Author ***@***.***>
Betreff: Re: [gmsafir/gmsafir] mesh error (Issue #14)


Upload your .geo and .g4s please (if not possible in this open forum, send it to me privately).

**Comment by MPSimu** [comment]
[case.g4s.txt](https://github.com/gmsafir/gmsafir/files/8713323/case.g4s.txt)
[part.STEP.txt](https://github.com/gmsafir/gmsafir/files/8713324/part.STEP.txt)
[case.geo.txt](https://github.com/gmsafir/gmsafir/files/8713325/case.geo.txt)

**Comment by MPSimu** [comment]
plase find enclosed all files

**Comment by MPSimu** [comment]
Hello, can you please have a look on files?

**Comment by MPSimu** [comment]
![1](https://user-images.githubusercontent.com/102736879/170486576-785e452e-096a-4307-ab04-3691dcfecc7f.JPG)
you know how to get rid of overlapping facets? I used command Coherence and also tried deleting faces but no luck

**Comment by gmsafir** [comment]
I need more info: did you try the 3D meshing with no special option (no Dilate...), just like I did ? Did it succeed ? The "overlapping facets" did occur with which .geo ? Did it change from the one I sent you ?

**Comment by MPSimu** [comment]
Hi, sorry for late reply..
It is different geo file. Without Dilation same problem persists.

**Comment by gmsafir** [comment]
Two things:
1/ on the previous case, with no special option (no Dilate), did you find the same result as me?
2/ on this new case, please provide me the .geo file

Don't forget that for a successfull debug, I always need to work exactly on the same case as you, to have a chance to reproduce the error that you get.

**Comment by MPSimu** [comment]
Hi, 
1) Yes. Additionally, I ''Optimize 3D'', so that nodes could become coincident.
2) In new case, without ''Coherence'' I don't see that error. I think it is necessary to merge all duplicates after importing the geometry (step file). Can I send you all the files privately?

**Comment by gmsafir** [comment]
ok I get clear your steps. ok, waiting for your file in private

**Comment by MPSimu** [comment]
I sent you.. please confirm

**Comment by gmsafir** [comment]
OK, your problem comes from the BooleanDifference with points, surfaces,... A simpler BooleanDifference is enough (with no Coherence):
BooleanDifference{ Volume{6}; Volume{14}; Volume{7}; Volume{13}; Delete; }{ Volume{1}; Volume{8}; Volume{3}; Volume{9}; Volume{12}; Volume{5}; Volume{10}; Volume{2}; Volume{11}; Volume{4}; Delete; }

The following script generates no error for me (only warnings because meshing is a bit too coarse, producing 2 or 3 very thin tets, you should probably refine it to avoid these):
[M1090412.geo.txt](https://github.com/gmsafir/gmsafir/files/8817975/M1090412.geo.txt)

**Comment by MPSimu** [comment]
Hi, thanks for your effort. I ran the script and mesh also generated but a volume is missing. It is the same volume whose faces are giving the mesh error.

**Comment by gmsafir** [comment]
Just after running "Mesh/Define/3D" (which gives 2 warnings for me on the .geo I sent you), I tried "Mesh/Define/Refine by splitting" and it removed the warnings for me. Can you please try this (with same .geo as I sent you, no additional change) ?

**Comment by MPSimu** [comment]
![Capture](https://user-images.githubusercontent.com/102736879/171562987-ea9e30dc-9198-4aef-83f4-2401b333bf65.JPG)
see the geometry.  A volume is not there.

**Comment by MPSimu** [comment]
I copied the same text from your file.

**Comment by gmsafir** [comment]
Ok thanks for the clarification on the file you use.
Did you try by clicking then "Mesh/Define/Refine by splitting" after "Mesh/Define/3D" ? Same result?

**Comment by MPSimu** [comment]
![image](https://user-images.githubusercontent.com/102736879/171564244-3c2cf0af-15d4-4443-8f86-4307f65d07a5.png)
yes I did mesh refinement as you suggested. There is no volume and mesh in the middle ( see red marked field)

**Comment by MPSimu** [comment]
Not only in middle. In fact, there are many volumes missing.

**Comment by gmsafir** [comment]
and are there still the errors (or warnings showing up? (even with "Refine" ?)

**Comment by MPSimu** [comment]
No

**Comment by gmsafir** [comment]
ok, now I have the same behavior as you. But I don't see any volume defined in the middle in the geometry : that is a problem in the geometry before meshing.
![mesh](https://user-images.githubusercontent.com/99477211/171565341-49ca11e0-411e-40b2-a80a-52edd677d8c5.PNG)
![just_geometry](https://user-images.githubusercontent.com/99477211/171565356-8e70f666-4e2a-425f-8872-e735cbe094b7.PNG)

**Comment by gmsafir** [comment]
(volumes are identified with a yellow sphere in their middle)

**Comment by gmsafir** [comment]
maybe I forgot some volumes when rewriting your BooleanDifference, can you check?

**Comment by MPSimu** [comment]
Before Booleandifference the geometry looks like this

![image](https://user-images.githubusercontent.com/102736879/171571387-78fcf50e-bbcf-4ede-bb1a-ac201bb41ab2.png)

**Comment by MPSimu** [comment]
could you please modify and send me? I have similar types of other geometries too. I need to find out what commands should be used.

**Comment by gmsafir** [comment]
Sorry but the current BooleanDifferences ends up with no volume in the middle, and this is not a bug, this is because you did not define it correctly, based on the volumes you want to intersect.
I cannot do the BooleanDifferences for you, since I don't know in practice which volumes you want to be intersected with which ones. Redo your BooleanDifferences with (1) only volumes (no points or surfaces) and (2) a good definition for you to get the correct volumes that you want to keep and to get meshed.

**Comment by MPSimu** [comment]
No Problem. I used the following command for meshing and it worked. No use of Boolean functions.

Coherence;
Mesh.AngleToleranceFacetOverlap = 0.005;
Mesh 3;

I know the how to create void in 2d analysis. Is it possible create Void in 3D analysis?

**Comment by gmsafir** [comment]
Great that it worked!
No, Void is restricted to 2D analysis

**Comment by rohit-linux** [comment]
I am trying to 3d mesh a geometry containing tunnel inside a mountainous topography.I am getting the same error as @MPSimu .But I have to use boolean fragment option to create hole (tunnel) in the mountain.Tried using
Mesh.AngleToleranceFacetOverlap=0.1
still did not work.Any help ,thank you
![image](https://github.com/user-attachments/assets/f06eee7b-7e14-4fda-b9f1-7af32a1f0e61)

**Comment by gmsafir** [comment]
upload .g4s and .geo, I will check

**Comment by rohit-linux** [comment]
[Topography and tunnels .geo.txt](https://github.com/user-attachments/files/18289369/Topography.and.tunnels.geo.txt)
I don't have .g4s file

**Comment by gmsafir** [comment]
Before the error in meshing, there are errors in the definition of the curves and surfaces ("could not add curve loop", "could not add plane surface"...), that need to be solved
![errors_before_meshing](https://github.com/user-attachments/assets/73d97f30-e74f-438d-be66-f72c70ffe314)

**Comment by rohit-linux** [comment]
it is running fine in my gmsh
![image](https://github.com/user-attachments/assets/2781754e-aa03-4087-a088-f2a413065563)

**Comment by gmsafir** [comment]
weird! When I put a printf for variable c2:
_c2=newll;
Printf("value of c2'%g'",c2);_
I get a value of 1522.
and 3 lines later, the following line :
_Curve Loop(c2+2)={1516,1517,1518,-1510,-1529,-1515,-1521};//(outer boundary of tunnel2)_
cannot get the curve number 1529.

What value do you get for c2 ?

**Comment by gmsafir** [comment]
Do you run with the very last version of gmsafir code?
