### ISSUE TITLE
Could not add plane surface

### ISSUE THREAD

**Issue by JMFranssen** [gmsafir/gmsafir#16]
The attached file is a simple "Thermal2D" problem made in GmSAFIR 2022-05-24..
I cannot see why GmSAFIR (in fact, GMSH here, as we are in the creation of the geometry) writes the error messages "Could not create surface" and "Could not add plane surface" twice, and Plane Surfaces (2) and (3) are not created.
I thought that this might have to do with the "Circle Arcs", but the problem remains if I replace the "circles arcs" by a line
[Model2DNS.geo.txt](https://github.com/gmsafir/gmsafir/files/8991232/Model2DNS.geo.txt)
.

**Comment by gmsafir** [comment]
Christophe explained the solution : points defining the surfaces (2) and (3) are not coplanar, so surfaces (2) and (3) cannot be Plane Surfaces.
