### ISSUE TITLE
Block is defined  twice

### ISSUE THREAD

**Issue by Kongzhu79** [gmsafir/gmsafir#17]
When doing a 2D thermal analysis, block temperatures were required  at certain nodes. When  doing this, all the blocks were defined twice which  caused the analysis to stop. Attached is an example of a simple analysis where the error is reproduced.

[BlocktestG4S.txt.txt](https://github.com/gmsafir/gmsafir/files/9001923/BlocktestG4S.txt.txt)
[BlocktestGEO.txt.txt](https://github.com/gmsafir/gmsafir/files/9001925/BlocktestGEO.txt.txt)

[version 2016c0_64 of SAFIR was used when trying to execute]

**Comment by gmsafir** [comment]
Problem is corrected with the newest version of gmsafir.py, please download it
