### ISSUE TITLE
Checking the values of properties

### ISSUE THREAD

**Issue by JMFranssen** [gmsafir/gmsafir#2]
If we click on a physical group, then on a particular property of this group, a window opens in which we can enter the values of the property. 
If, later on, we come back to this property of this group, the values that appear in the window are not those of the property of this group, but the last values that appeared in this window, possibly when they where given to another group. This makes it impossible to verify the values that were given previously for a property in a specific group.
Would it be possible to change that in a way that the values that appear in the window are those given previously to the property of this group ?

**Comment by gmsafir** [comment]
it should run properly with the newest version
