### ISSUE TITLE
gmsafir crashes when creating the .in file for a structural 3D shell calculation

### ISSUE THREAD

**Issue by marpitt** [gmsafir/gmsafir#22]
When i try to create the .in file for a structural 3D modell containing shell elements gmsafir crashes. I tried multiple different shell models. Even when i try to recreate the concrete slab from the youtube video GmSAFIR 13, the program crashes as soon as i hit the "create .in" button. The only difference to the model in the video is, that i did not define rebars for the slab. I attached my model, based on the youtube video GmSAFIR 13, to this message.
[test.g4s.txt](https://github.com/gmsafir/gmsafir/files/9234572/test.g4s.txt)
[test.geo.txt](https://github.com/gmsafir/gmsafir/files/9234573/test.geo.txt)

**Comment by gmsafir** [comment]
Please also upload your steg_tsh.tsh (rename it also .txt at the end)

**Comment by marpitt** [comment]
[steg_tsh.TSH.txt](https://github.com/gmsafir/gmsafir/files/9240147/steg_tsh.TSH.txt)

**Comment by gmsafir** [comment]
The new uploaded version of code shall work correctly
