### ISSUE TITLE
Sintax error at the starting 

### ISSUE THREAD

**Issue by renmatte** [gmsafir/gmsafir#24]
tried to install gmsafir but when I try to start gmsafir it give me this error :

PS C:\Users\renma> python.exe C:\gmsafir\gmsafir.py
  File "C:\gmsafir\gmsafir.py", line 67
    <title>gmsafir/gmsafir.py at master · gmsafir/gmsafir · GitHub</title>
                                                           ^
SyntaxError: invalid character '·' (U+00B7)
[error.pdf](https://github.com/gmsafir/gmsafir/files/9387137/error.pdf)

Any idea about this error? I have installed  python version 3.10.6

Thamk you

**Comment by renmatte** [comment]
Now I replaced python 3.10.6 with python version 3.9.6 and the error is different at the line 8:

PS C:\Users\renma> gmsafir
  File "c:\gmsafir\gmsafir.py", line 8
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
PS C:\Users\renma>

**Comment by gmsafir** [comment]
You downloaded gmsafir.py in a wrong way. Go to page : https://github.com/gmsafir/gmsafir, and click on green button "Code". Select "Download ZIP"

**Comment by renmatte** [comment]
ok. Now it works. I'm sorry. Thanks
