### ISSUE TITLE
Error in KSOLID - Determinant of the jacobian

### ISSUE THREAD

**Issue by kwh05** [gmsafir/gmsafir#25]
I cant get the attached model to run through SAFIR without the error message

![image](https://user-images.githubusercontent.com/110048071/186648968-449734a4-98cc-4adb-a5c5-1895c8a26c7f.png)

i have paid careful attention to create my surfaces going anti clockwise 

are you able to assist
[STEEL BEAM IN.txt](https://github.com/gmsafir/gmsafir/files/9424049/STEEL.BEAM.IN.txt)
[STEEL BEAM GEO.txt](https://github.com/gmsafir/gmsafir/files/9424050/STEEL.BEAM.GEO.txt)
[STEEL BEAM g4s.txt](https://github.com/gmsafir/gmsafir/files/9424052/STEEL.BEAM.g4s.txt)
?

**Comment by gmsafir** [comment]
When looking at the normals of your surfaces, you see that many surfaces are not anticlockwise
![Capture](https://user-images.githubusercontent.com/99477211/186662207-7d050bfc-5978-4287-8257-cd04f639e5ce.JPG)
