### ISSUE TITLE
Issues in following GmSAFIR installation guide - GMSH Python library

### ISSUE THREAD

**Issue by chkevinly** [gmsafir/gmsafir#27]
Hi, I am unable to complete step 4 in the installation. I am using Python 3.10.7. The issue is that pip install lines cannot be used (please find the error code shown)

![image](https://user-images.githubusercontent.com/113345605/189909167-89e953d4-d8ab-4c01-afa9-4c86f47e0412.png)

even if doing “python.exe –m pip install gmsh”, it did not show any error during installation, importing gmsh in python returns this following error:

![image](https://user-images.githubusercontent.com/113345605/189909199-9a836e69-46c8-4c20-80e9-18405a39483c.png)

Thank you

**Comment by gmsafir** [comment]
Hi, you got an extra <space> character that should be removed in the line:
python.exe -m pip install -i https://gmsh.info/python-packages --<space>force-reinstall --no-cache-dir gmsh-dev

**Comment by gmsafir** [comment]
But maybe it will not be enough to remove the bug, tell me

**Comment by chkevinly** [comment]
thank you for your reply. I have used this line you mentioned, but it still does not work.

![image](https://user-images.githubusercontent.com/113345605/196111936-54cb4464-500a-4baf-82d6-957747c964ee.png)

Would you please kindly clarify which character I need to remove? I removed the space between -- and force and it is still not working.

Thank you

**Comment by chkevinly** [comment]
Hi, managed to solve the issue by changing "python.exe -m pip install -i https://gmsh.info/python-packages --force-reinstall --no-cache-dir gmsh-dev" into "python.exe -m pip install -i https://gmsh.info/python-packages --force-reinstall --no-cache-dir gmsh"

will this alter the functionality?

**Comment by gmsafir** [comment]
No indeed, packages gmsh and gmsh-dev have now been merged into a single one: gmsh. It will work properly
