### ISSUE TITLE
User_steel for 2D structural analysis

### ISSUE THREAD

**Issue by nelly-22** [gmsafir/gmsafir#29]
Hello,
I would like to do a 2D structural analysis for an IPE600 beam with an user defined material. 

Before, I did a 2D thermal analysis of the IPE600. Then I changed in the "2D_beam_IN" file the material "steelec3" to "user_steel". For the "user_steel.txt"-file I took the example of the manual of safir 2022-mechanical page 52 (see below) to see if safir calculates. 
![grafik](https://user-images.githubusercontent.com/108728919/191759802-99db4922-ffcd-4234-a21b-87bf8f1f6477.png)

But Safir shell gives always this error:
![grafik](https://user-images.githubusercontent.com/108728919/191760039-ad482f7f-f87f-438f-9539-428847b1caed.png)

Can you help me? Thanks and best regards,
Nelly

[USER_STEEL.txt](https://github.com/gmsafir/gmsafir/files/9626219/USER_STEEL.txt)
[IPE600.TEM.txt](https://github.com/gmsafir/gmsafir/files/9626220/IPE600.TEM.txt)
[2D_beam.IN.txt](https://github.com/gmsafir/gmsafir/files/9626224/2D_beam.IN.txt)
[2D_beam.geo.txt](https://github.com/gmsafir/gmsafir/files/9626226/2D_beam.geo.txt)
[2D_beam.g4s.txt](https://github.com/gmsafir/gmsafir/files/9626227/2D_beam.g4s.txt)

**Comment by nelly-22** [comment]
PS: I'm using the demo version

**Comment by JMFranssen** [comment]
Nelly,

your input file is correct as it runs correctly on my computer. The problem is that I cannot reproduce your bug.
As this is a matter of SAFIR and not of GmSAFIR, drop me a message on safir@uliege.be and I will send you the latest version of SAFIR demo for you to test whether this bug still appears on your computer.

Regards

J-M Franssen

**Comment by nelly-22** [comment]
Hello, 
with the lastest version of SAFIR the input file runs now. Thank you!
