### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by MPSimu** [gmsafir/gmsafir#3]
Hello, I created input file with GmSAFIR. While running it no solution is genearted. I can't attach .geo and .in files here to send you.

**Comment by gmsafir** [comment]
I took the liberty to upload the files.
The formats suported are .txt for text files, so I added .txt as additional suffix. Remove these suffixes once downloaded
[D08.geo.txt](https://github.com/gmsafir/gmsafir/files/8396456/D08.geo.txt)
[D08.IN.txt](https://github.com/gmsafir/gmsafir/files/8396457/D08.IN.txt)

**Comment by gmsafir** [comment]
I ran this case successfully with version SAFIR2022a0.exe.

**Comment by MPSimu** [comment]
I could also run it with the new version. thanks
