### ISSUE TITLE
GMSH Python library

### ISSUE THREAD

**Issue by jeromeV62** [gmsafir/gmsafir#31]
Hello, 

In order to install GmSafir and the GMSH Python library, I follow the installation manuel but I stop at §4. The computer returns me the message :

![installation Safir 2022 a2](https://user-images.githubusercontent.com/114664103/193020936-5c5e9f92-a205-43df-bbe2-6f07c6c4adbc.PNG)

Someone could helps me ? 
Thanks a lot.

**Comment by chkevinly** [comment]
in my case, it works if i change "gmsh-dev" into "gmsh" I don't know how it will affect the functionality tho

**Comment by gmsafir** [comment]
Indeed, the gmsh and gmsh-dev packages have now been merged into a single one "gmsh", so it will work properly
