### ISSUE TITLE
Unable to analyze the .IN file

### ISSUE THREAD

**Issue by karthikmn12331** [gmsafir/gmsafir#32]
Hello, 

I've been working on an I-section with insulation. All the material properties and frontiers have been set and meshed. However, the safir shell fails to calculate with the following errors.

 SAFIR version 2022 is running.
 Please type "FILENAME" of "FILENAME.IN" :   SAFIR is allocating memory
forrtl: severe (59): list-directed I/O syntax error, unit -5, file Internal List-Directed Read
Image              PC                Routine            Line        Source             
safir.exe          00007FF72F493114  Unknown               Unknown  Unknown
safir.exe          00007FF72F4FD4D4  Unknown               Unknown  Unknown
safir.exe          00007FF72F388EC8  Unknown               Unknown  Unknown
safir.exe          00007FF72F0DAEEC  Unknown               Unknown  Unknown
safir.exe          00007FF72F4666D5  Unknown               Unknown  Unknown
safir.exe          00007FF72F28D097  Unknown               Unknown  Unknown
safir.exe          00007FF72F37592B  Unknown               Unknown  Unknown
safir.exe          00007FF72FA0DE2E  Unknown               Unknown  Unknown
safir.exe          00007FF734F94CB4  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFA246F7034  Unknown               Unknown  Unknown
ntdll.dll          00007FFA25CC26A1  Unknown               Unknown  Unknown
CylanceMemDef64.d  00007FFA1A06C329  Unknown               Unknown  Unknown
CylanceMemDef64.d  00007FFA1A06F62B  Unknown               Unknown  Unknown

I'm unable to figure out the cause for this error. The .IN file used is attached here and would be great to know if there are any user errors pertaining to this issue.

[thermal_I.txt](https://github.com/gmsafir/gmsafir/files/9676083/thermal_I.txt)

**Comment by kowalskiw** [comment]
Hello,

I am pretty sure that you meshed your model in the wrong way:

1. There is no link between insulation finite elements (FE) and steel section FE.
2. Insulation should be adjacent to the section. In your model this is another fully-filled  "I-section" of insulation material interfering with the steel section (see the picture).
3. Mesh seems to be quite rough.

![obraz](https://user-images.githubusercontent.com/27781986/193101619-cc6f7a5a-6f6d-4742-b517-1d11b927b53c.png)
![obraz](https://user-images.githubusercontent.com/27781986/193104626-2b80ed26-4076-422a-b846-59abf6792533.png)

I've changed following lines in your file:
```
MATERIALS
INSULATION
0.313 1.17 40 5 100 110 25 4 0.92 insulation
STEELEC3EN
25 4 0.7 mat1
```
to:
```
MATERIALS
INSULATION
0.313 1.17 40 5 100 110 25 4 0.92
STEELEC3EN
25 4 0.7
```
and it works just fine.

Best regards,
Wojciech

**Comment by karthikmn12331** [comment]
Hello Wojciech, 

Thank you for taking your time and providing me with a solution. I clearly remember extruding the surfaces separately to create the volumes and I believe I should avoid doing that. The file does compute and I shall note the points that you mentioned and fix them. 

Thanks once again!

Best regards,

Karthik

**Comment by kowalskiw** [comment]
I think this issue can be closed as it doesn't concern gmsafir in fact.
