### ISSUE TITLE
Thermal and mechanical analysis of a composite beam

### ISSUE THREAD

**Issue by nelly-22** [gmsafir/gmsafir#35]
Hello,

I did a 2D-thermal analysis of a composite cross section (steel and concrete) (files: Th_OhnePutz_ETK.IN, Th_OhnePutz_ETK.TEM,..). See the picture below.
![grafik](https://user-images.githubusercontent.com/108728919/196723348-cea2cb54-4a73-4a61-b91d-a511de0e9819.png)

After that I did a 2D mechanical analysis of a single-span beam which has the same cross section like the one of the thermal analysis. So I transfered the TEM file. The materials are user-defined, so I have the files "User_steel" and "User_conc". 
For the summary I wanted to regard the stresses of the beam in the middle (beam 7 and 8 with max. stresses) in the different fibers. 
![grafik](https://user-images.githubusercontent.com/108728919/196724675-a4e2572d-ef16-4ba8-bc5a-6d02556fb5ef.png)

My calculation stops at 2300s. Now I don't know exactly how I should interprete this result. I think the steel will collapse.
Does Safir stops, when the yield strength (dependent of the temperature) is reached in one fiber or when all fibers reach the yield strength?
Thank you very much!

[USER_CONC.txt](https://github.com/gmsafir/gmsafir/files/9821600/USER_CONC.txt)
[USER_STEEL.txt](https://github.com/gmsafir/gmsafir/files/9821601/USER_STEEL.txt)
[Str_ohneP_ETK.IN.txt](https://github.com/gmsafir/gmsafir/files/9821602/Str_ohneP_ETK.IN.txt)
[Str_ohneP_ETK.OUT.txt](https://github.com/gmsafir/gmsafir/files/9821604/Str_ohneP_ETK.OUT.txt)
[Str_ohneP_ETK.XML.txt](https://github.com/gmsafir/gmsafir/files/9821609/Str_ohneP_ETK.XML.txt)
[Th_OhnePutz_ETK.IN.txt](https://github.com/gmsafir/gmsafir/files/9821612/Th_OhnePutz_ETK.IN.txt)
[Th_OhnePutz_ETK.OUT.txt](https://github.com/gmsafir/gmsafir/files/9821613/Th_OhnePutz_ETK.OUT.txt)
[Th_OhnePutz_ETK.TEM.txt](https://github.com/gmsafir/gmsafir/files/9821614/Th_OhnePutz_ETK.TEM.txt)
[Th_OhnePutz_ETK.XML.txt](https://github.com/gmsafir/gmsafir/files/9821615/Th_OhnePutz_ETK.XML.txt)

**Comment by gmsafir** [comment]
This comes initially as a SAFIR execution problem. Please, post a non-anonymous message on SAFIR hotline :  [SAFIR@uliege.be](mailto:SAFIR@uliege.be)

**Comment by nelly-22** [comment]
Thank you for the quick answer!
