### ISSUE TITLE
Error with frontiers in input file

### ISSUE THREAD

**Issue by karthikmn12331** [gmsafir/gmsafir#37]
Hello, 

I'm currently running the latest version of GmSafir and version 1.2.0 of Safir shell. 
I have an issue with the input file containing frontier elements in multiple lines with the designation of 

"NO NO HYDROCARB - HYDROCARB NO NO"

The presence of '-' prevents safir shell from analyzing the file. On GmSafir, the errors are visible when assigning the frontiers to the surfaces. Also, the error of Diag-capa and comeback are present even on the newest version of Gmsafir. 

I have attached the input file here. Kindly go through the same and help in resolving the issue. 

Karthik Nagendra
[thermal.txt](https://github.com/gmsafir/gmsafir/files/9861730/thermal.txt)

**Comment by gmsafir** [comment]
please provide your files .geo and .g4s, after renaming them .geo.txt and .g4s.txt

**Comment by karthikmn12331** [comment]
[thermalWR537INS.geo.txt](https://github.com/gmsafir/gmsafir/files/9867190/thermalWR537INS.geo.txt)
[thermalWR537INS.g4s.txt](https://github.com/gmsafir/gmsafir/files/9867194/thermalWR537INS.g4s.txt)

Here are the files. Please note that all the frontiers/materials have not been applied. However, the error frontiers are visible.

**Comment by gmsafir** [comment]
Do you have the latest GmSAFIR version? if not the case, please download this new one.
I am asking because when executing the latest version, GmSAFIR does not generate the .IN file: it complains about the fact that you have volumes with no material defined, namely all volumes 8-74 (except 32 and 67).

**Comment by gmsafir** [comment]
Provide either a version of .g4s file with all volumes with materials, or a much simpler case (.geo and .g4s) with the same problem

**Comment by karthikmn12331** [comment]
I have the latest version (2022-09-21 Version 1.0). 
[properties.txt](https://github.com/gmsafir/gmsafir/files/9869284/properties.txt)
[WR537INS.g4s.txt](https://github.com/gmsafir/gmsafir/files/9869285/WR537INS.g4s.txt)
[WR537INS.geo.txt](https://github.com/gmsafir/gmsafir/files/9869286/WR537INS.geo.txt)
[WR537INS.txt](https://github.com/gmsafir/gmsafir/files/9869287/WR537INS.txt)

**Comment by gmsafir** [comment]
Please download the newest version of GmSAFIR (I just corrected a bug) and redo the allocation of all ins and steel to volumes. It shall work better.

**Comment by karthikmn12331** [comment]
That will be the solution for the primary error? or has the bug corrected the data collection in the G4S file?

**Comment by gmsafir** [comment]
No, not the solution for the initial error, but the bug correction indeed corrects the data collection in G4S file. It may hide another bug on the frontier, unless the bugged data collection was generating the bug on the frontier.

**Comment by karthikmn12331** [comment]
Here are the files,


[WR537INS.g4s.txt](https://github.com/gmsafir/gmsafir/files/9879127/WR537INS.g4s.txt)
[WR537INS.geo.txt](https://github.com/gmsafir/gmsafir/files/9879131/WR537INS.geo.txt)
[WR537INS2.IN.txt](https://github.com/gmsafir/gmsafir/files/9879137/WR537INS2.IN.txt)

**Comment by gmsafir** [comment]
And if I click multiple times on the "Add/Update" of HYDROCARB frontier constraint for Surface 49, it still stores it only as mono-line in the G4S file.

**Comment by karthikmn12331** [comment]
When I create the model and assign the frontiers, the error of '-' does not show on the GUI. However, once meshed and the input file is generated, it contains '-'. When I reload the script, it shows the error in the GUI. I don't understand how just one particular surface (previously it was more than one surface) has this error while I apply the frontiers the same way to the rest of the model. I initially assumed it was due to the grouping of the surfaces which might have caused the error, but it wasn't and even though I painstakingly applied frontiers to all the surfaces, it still had the errors. Depending on the refinement of the mesh, the number of lines generated in the input increase exponentially. Currently I run the file through a refining script on python to identify and remove the errors, so I don't do them manually.  I aim to remodel the entire project once again and try to see if there are any overlapping surfaces within the geometry itself. 

I recently reloaded the script and reupdated the frontier on surface 49 and it seems as though the error disappeared. But as I run it through safir shell, it points to a jacobian error (which didn't exist before) with the surfaces being in clockwise direction. And from inspection, it is surface 49. But how this error induced the '-' issue or vice versa is like a worm in my head.

**Comment by gmsafir** [comment]
Yes, forget the '-' error, it is just a consequence of another initial issue. the problem originates from the first time that you assign all frontiers and materials. This generates automatically the G4S file, and it writes there multilines instead of monolines. All other problems (presence of '-' in the IN file, error in the GUI...) are just consequences of this original issue.

I don't understand how your assignment from the GUI menus generates these multilines in the G4S file.
The '-' error will disappear if your G4S file only contains a monoline in each definition, and not multilines.

Please, provide the last G4S and GEO files for the problem of Jacobian error, which might be an independent problem.

**Comment by karthikmn12331** [comment]
I'm confused as well. However, as you mentioned, I can ignore the '-' errors. Kindly help with the reversal of tangents (Surface 49) from the below provided files.  
[WR537INS4.geo.txt](https://github.com/gmsafir/gmsafir/files/9899838/WR537INS4.geo.txt)

[WR537INS4.g4s.txt](https://github.com/gmsafir/gmsafir/files/9899844/WR537INS4.g4s.txt)

Thank you!

**Comment by gmsafir** [comment]
Please, try with new updated version of GmSAFIR, it shall generate a .IN that works correctly with SAFIR2022
