### ISSUE TITLE
Importing dxf files

### ISSUE THREAD

**Issue by andreamarinovvf** [gmsafir/gmsafir#39]
Dear GmSAFIR developers,
I can find the command to import dxf files, that can help me in defining the geometry of sections or structures.
I found the possibility to open many kind of other files, as iges, for instance.
Is there this command? If not, are you going to add it?
Thank you in advance,
Andrea Marino

**Comment by gmsafir** [comment]
Hi, no the dxf format is not yet supported, and not yet foreseen to be supported in a near future. If you have a software producing dxf files, isn't it possible to export in iges format?

**Comment by andreamarinovvf** [comment]
Thanks for the information. I tried to open a file in dxf format and then to export it in iges format. This has been possible using advanced software like Rhinoceros, although I didn't check if the imported geometry is really ok for GmSafir. Using common app like autocad, this export wasn't possible. Obviously I don't know all the apps able to export a dxf or a dwg file in iges format. I'll keep you informed about the question.

**Comment by gmsafir** [comment]
Thx for your update

**Comment by soswxc** [comment]
There is ezdxf library in python, it can open and write dxf files, checkout  Conjugate_cam project in my profile
maybe it'll help
