### ISSUE TITLE
Filename.in 

### ISSUE THREAD

**Issue by LGCajot** [gmsafir/gmsafir#4]
Hi,
When asking to create a file dalleiso.in, GMsafir has created dalleISO.in. I have doublechecked. The name in the geo file is dalleiso with iso in small letters. But in my directory the file dalleISO with ISO in capital letters has been created!
I have tried to join the files geo and gs4 but this format is not accepted by this tool.
It is not really an issue. Only to inform you.

**Comment by gmsafir** [comment]
Could you please try again uploading the files? But before uploading, please add a suffix ".txt" to their filenames. This format is suported by GIThub

**Comment by LGCajot** [comment]
[dalleg4s.txt](https://github.com/gmsafir/gmsafir/files/8402174/dalleg4s.txt)
[dallegeo.txt](https://github.com/gmsafir/gmsafir/files/8402175/dallegeo.txt)

Thanks for your quick answer; As requested, please find here attached the files with extension .txt. I have added gs4 and geo in the filename.
