### ISSUE TITLE
Tension ductility parameter for material Silcoetc2D

### ISSUE THREAD

**Issue by nelly-22** [gmsafir/gmsafir#42]
Hello,

I'm doing a 3D mechanical analysis of a composite slab with steel beams and I have a question concerning the material properties.

I don't understand exactly what is the "tensile ductility parameter" of the concrete "SILCOETC2D". The recommended value is 400 N/m². In the example file "Reinforced concrete slab on unprotected steel beams developing tensile membrane action" (from https://mars.jhu.edu/safir/worked-examples/ ) is the value 1200 N/m² for example. 

Because I can't insert the tensile strength of my concrete steel, I first thought that the "tensile ductility parameter" is the fracture stress of the reinforcement. But then the unity of N/m² doesn't fit..

Can you explain me the definition?

Thank you and kind regards
Nelly Kamens

**Comment by gmsafir** [comment]
Hi Nelly, as you indicate, this is a matter of SAFIR, so please ask your question at SAFIR hotline : [SAFIR@uliege.be](mailto:SAFIR@uliege.be)
