### ISSUE TITLE
Installation and gmsh import

### ISSUE THREAD

**Issue by miguelmaso** [gmsafir/gmsafir#43]
Hi, I'm trying to use `gmsafir`, but I've faced the following error with `gmsh`:

```shell
python3 .\gmsafir.py
Traceback (most recent call last):
  File "C:\Users\Miguel.Maso\Downloads\GmSafir\gmsafir.py", line 3, in <module>
    import gmsh
  File "C:\Users\Miguel.Maso\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gmsh.py", line 53, in <module>
    lib = CDLL(libpath)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable
```

Windows10
Python3.10

Can someone help me with installation?

**Comment by gmsafir** [comment]
please retry with python3.7

**Comment by miguelmaso** [comment]
@gmsafir thanks for your response. I will try with python3.7
However, for another project I need python3.8 or newer, and I don't like the idea of having several python versions on a windows environment... Furthermore, python 3.7 will reach its eol on July 23

**Comment by Silvio-Re** [comment]
Hello @miguelmaso gmsafir does also run with Python 3.9.13 with my setup.
I would strongly suggest to use dedicated virtual python environment to deal with the dependencies of different projects.

**Comment by gmsafir** [comment]
The problem occuring at install with python>=3.8 in for particular Windows setups, currently unclear. I am currently asking the gmsh developer about this issue

**Comment by miguelmaso** [comment]
I've tried to reinstall it again:
- `python3.7` successfull
- `python3.11` successfull

I don't know what is the origin of the previous issue, but for me it's solved. Reopen if you need to track this issue for particular Windows setups.

Thanks
