### ISSUE TITLE
Question about generating a .IN file automatically without going through gmsh

### ISSUE THREAD

**Issue by CassAdri** [gmsafir/gmsafir#46]
Hello,

I have written a Python code for generating .geo and .g4s file automatically given parameters entered by a user. Is there a way for generating automatically a .IN file without using the "traditional way" (_Gmsh --> Files--> Open --> Mesh --> Create .IN file_) ?

My idea was the following one : I would like to call in my python script one (or more) function(s) written in gmsafir.py, I already looked into the script but I did not understand which function was for what.

Can you help me, solving this problem ?

Thanks you for your time.

Best regards

**Comment by gmsafir** [comment]
The "batch mode" was developed very early, hope it is still working.
Download the latest GmSAFIR version and run in command line after entering the directory where you have your GEO and G4S files with following command:
python.exe [full_path]/gmsafir.py -nopopup
That should generate the IN file without opening the GUI

**Comment by CassAdri** [comment]
Thanks, for your answer,

I have tried something but it does not work, maybe it is because I did not clearly understand what you explained. 
My .geo and .g4s files have an absolute path, namely : _E:\Adriano_Cassella\Exemple.geo and E:\Adriano_Cassella\Exemple.g4s_ and the gmsafir.py have the following path : _C:\Users\stagiaire\gmsafir-master_V2022-11-08\gmsafir.py_ .
What I have done is the following procedure :

- I opened the windows command prompt 
- I wrote : python.exe E:\Adriano_Cassella\Exemple.geo/gmsafir.py -nopopup
And this did not worked. Should I have the same access path for the .geo, .g4s and gmsafir.py files ?

Thanks again for your help

**Comment by CassAdri** [comment]
Sorry, I have maybe written to fast.
I have tried another procedure manually and it works now.
Keeping the same locations as before for my files I have done the following :

- Open Windows Command prompt
- type : _python.exe C:\Users\stagiaire\gmsafir-master_V2022-11-08\gmsafir.py E:\Adriano_Cassella -nopopup_
the first path is for the script gmsafir.py and the second path is the folder containing my .geo file.

Now I will try to do this operation not manually but directly in a python script. It should work . Thank again for your help.

**Comment by gmsafir** [comment]
The steps are :
1/ open the windows command prompt
2/ enter a command to enter the directory where you have the G4S file and GEO file: cd [ful_path_to_directory]
3/ type : python.exe C:\Users\stagiaire\gmsafir-master_V2022-11-08\gmsafir.py E:\Adriano_Cassella -nopopup

Let me know iif it works

**Comment by CassAdri** [comment]
Yes it works very well,
but how to make it also works even if there are multiple .geo files in the same folder? For example, if I have Exemple.geo linked to Exemple.g4s and Test.geo linked to Test.g4s.
Is it possible to use the "batch mode" when 2 .geo files are in the same folder ?

Thanks

**Comment by gmsafir** [comment]
did you try the same steps 1-2-3 above, except changing step 3 with :
python.exe C:\Users\stagiaire\gmsafir-master_V2022-11-08\gmsafir.py [your_geo_file_name] -nopopup
?

**Comment by CassAdri** [comment]
Yes I have tried and it does not work

**Comment by gmsafir** [comment]
which error outputs do you get in the command window ?

**Comment by CassAdri** [comment]
![image](https://user-images.githubusercontent.com/100410154/205302675-4a85169d-ad66-42c7-a204-861e9474b308.png)
I think it just does not recognize the command

**Comment by gmsafir** [comment]
I modified the treatment.
With same syntax "python.exe [full_path]/gmsafir.py [full_path_directory] -nopopup", 
Step 2 is not necessary anymore, you can launch directly when entering the command window, just provide the full_path_directory.
In this directory, all couples (geo,g4s) files will be treated. The single g4s (no associated geo) or single geo (no associatied g4s) will not be treated.
Download the newest version and enjoy!
