### ISSUE TITLE
Extra node created on top of existing node

### ISSUE THREAD

**Issue by caribus** [gmsafir/gmsafir#49]
When doing a 3D structural analysis using SAFIR 2022.a.3 an extra node is created. In a previous version of SAFIR (2019), this node was created out of the structural element. However, in the .IN file generated by GmSAFIR the node in our case coincides with one of the nodes of the structural element. This is shown in the image below where NODE 8 is the extra node that has the same coordinates that NODE 7.

![image](https://user-images.githubusercontent.com/120425088/207169290-cde7a3ce-8fe6-43be-a59d-5d8bc544d6a9.png)

When conducting the analysis of this structural element the following error is raised as a result.

```
<<ERROR from SAFIR in subr. ROTINIBEAM.
   There is a problem in the definition of beam element     1.
   The 4th node of this element is on (or at a small distance from) the line that joints nodes 1 and 3.
   It is thus not possible for SAFIR to find the orientation of the local axis z of this beam element.>>
```

To solve this issue with the mesh generation, the .IN file must be edited by hand to change the coordinates of NODE 8 to place the node out of the structural element (see image below).

![image](https://user-images.githubusercontent.com/120425088/207169595-725c5479-8d08-4860-b0fd-0587ed9e340e.png)

Find attached the corresponding `.GEO` and `.G4S` files.

[structural_case.g4s.txt](https://github.com/gmsafir/gmsafir/files/10212546/structural_case.g4s.txt)
[structural_case.geo.txt](https://github.com/gmsafir/gmsafir/files/10212547/structural_case.geo.txt)

**Comment by gmsafir** [comment]
Apart the fact that I miss the .TEM file to really complete the creation of the .IN file for your meca run, I get an error message from GmSAFIR: "tangent axis and user-defined Y-Axis (of local axis) cannot be collinear"
Do you use the latest version of GmSAFIR? If not, please download the latest version, since a bug was corrected somewhere last september or october concerning the local axis.
If the problem still persists, please upload additionally the .TEM file

**Comment by caribus** [comment]
Thank you for your quick response. Yes, we are currently using the latest version of GmSAFIR. 
When defining the local axis we do get the warning that you mentioned: "tangent axis and user-defined Y-Axis (of local axis) cannot be collinear", but this warning does not appear in the .IN file and, despite the warning, the analysis can be run.
Please, find attached the corresponding .TEM file as well as the .OUT file where the error appeared.
[calentamiento_completo.txt](https://github.com/gmsafir/gmsafir/files/10217638/calentamiento_completo.txt)

**Comment by gmsafir** [comment]
Your beam follows the global z-axis, so his local x'-axis is this z-axis. Then you request as local y'-axis ... the z-axis. Indeed, x'-axis and y'-axis are collinear, and thus a point cannot be defined by GmSAFIR outside of the z-axis. What is wrong there is that GmSAFIR should not create the IN file until you have not provide a y'-axis not collinear to the x'-axis. I corrected that in the new version just uploaded
