### ISSUE TITLE
Loss of input fire curve in g4s when the thermal analysis finished.

### ISSUE THREAD

**Issue by Malcolmfxy** [gmsafir/gmsafir#50]
[](url)Hi,
When I run the 2d thermal analysis with user-defined fire curve, I found that I have to modify the g4s file again and again as long as the previous analysis was finished.
For example:
Before the analysis, the definition of the physical curve in g4s file is:

Curve - Frontier Constraint(Physical Curve 32) = {
Temperature : User-defined
File for Temperature : fire.txt
}
when the analysis is finished, it will change to

Curve - Frontier Constraint(Physical Curve 32) = {
Temperature : User-defined
}
so I have to modify this file every time when I want to resubmit my job in the gmsafir.

attached are my fire curve and geo and g4s files. (I changed their suffix to .txt for uploading.)

[w1631grider - copy.txt](https://github.com/gmsafir/gmsafir/files/10242229/w1631grider.-.copy.txt)
[w1631grider - copygeo.txt](https://github.com/gmsafir/gmsafir/files/10242230/w1631grider.-.copygeo.txt)
[fire.txt](https://github.com/gmsafir/gmsafir/files/10242232/fire.txt)

**Comment by gmsafir** [comment]
I just fixed a bug. Please download the new version

**Comment by Malcolmfxy** [comment]
thanks very much, but this bug still exists.

**Comment by gmsafir** [comment]
I am on it to fix it, hopefully still before end of the year

**Comment by gmsafir** [comment]
Check with new updated version, problem shall be fixed

**Comment by Malcolmfxy** [comment]
thanks very much, in the newest version, it has been fixed.
