### ISSUE TITLE
Error when using the MAKE.TSH option

### ISSUE THREAD

**Issue by CassAdri** [gmsafir/gmsafir#52]
Hello,
I have an issue when using the MAKE.TSH option in gmsafir. I created a 2D thermal section with one material (Concrete) and I assigned a FISO curve on the bottom edge of my geometry. Moreover, I used the transfinite option to construct a structured mesh. My issue is that when I click on _Create .IN file_ I get the following error message : 
**Error   : Problem in verifyRectangleGeomTSH:can only concatenate str (not "numpy.int32") to str**

My _gmsafir.py_ version is 2022-12-05 - Version 1.0.
I share with you the .geo and .g4s files pasted in .txt files.
[CofraShell.geo.txt](https://github.com/gmsafir/gmsafir/files/10260618/CofraShell.geo.txt)
[Cofra_shell.g4s.txt](https://github.com/gmsafir/gmsafir/files/10260619/Cofra_shell.g4s.txt)

Hope you can help me

Thanks for advance

Best regards

**Comment by gmsafir** [comment]
there was a bug. Now last updated version shall work correctly
