### ISSUE TITLE
Gmsafir crashes when with multiple curves

### ISSUE THREAD

**Issue by AlexMELAB** [gmsafir/gmsafir#53]
Hi,

I'm having an issue on larger models.
When I have more than 6 distinct mass or material parameters in my g4s file the entire gmsafir application crashes when trying to view these on the viewer.
Have been unable to work out any way around this and it does not appear to be dependent on what the inputs are, just the total number.

Thanks for any help.

**Comment by gmsafir** [comment]
Hi, please upload your .geo and .g4s files allowing to reproduce the issue (change names from .geo and .g4s to .geo.txt and .g4s.txt, or alternatively make a .zip archive).

**Comment by AlexMELAB** [comment]
[BrewGround_1-g4s.txt](https://github.com/gmsafir/gmsafir/files/10283889/BrewGround_1-g4s.txt)
[BrewGround_1-geo.txt](https://github.com/gmsafir/gmsafir/files/10283890/BrewGround_1-geo.txt)

This is a working version which is not complete - no loads etc.
If there are more than 5 mass inputs in the g4s or more than 11 curve sections it crashes when hitting the respective view button.

**Comment by gmsafir** [comment]
indicate what precise load yuo are trying to put on what precise beam number, that makes it crash

**Comment by AlexMELAB** [comment]
No specific load causes it. These represent around 6 beam profiles and 4 column profiles each with a specific mass.
Any combination of these mass inputs causes the crash unless there are less than 6 total.
The intendent beam loads are in the g4s file.

**Comment by JMFranssen** [comment]
There was also an issue in SAFIR if the number of lines in the different files that describe the user defined functions in a thermal analysis was not the same. This has been fixed now.
