### ISSUE TITLE
Zoom Extent in 2D elements

### ISSUE THREAD

**Issue by Lelli-INGENI** [gmsafir/gmsafir#56]
When creating a single line element (i.e. a column) it is impossible to show it in full extent view. Scrolling zoom does not end.
The views are automatically adapted when entering a node outside the line, but the node must be removed before lanching the .in file

**Comment by gmsafir** [comment]
please provide the .geo file containing the definition of the column

**Comment by gmsafir** [comment]
(change suffix .geo of file into .get.txt)

**Comment by Lelli-INGENI** [comment]
Hi,

Please find the file attached.


Regards


LORENZO LELLI
DIRECTEUR

***@***.***

De : gmsafir ***@***.***>
Envoyé : samedi, 11 février 2023 20:36
À : gmsafir/gmsafir ***@***.***>
Cc : Lelli, Lorenzo ***@***.***>; Author ***@***.***>
Objet : Re: [gmsafir/gmsafir] Zoom Extent in 2D elements (Issue #56)

This is the first time you've received an email from this sender. Make sure this is someone you trust.

please provide the .geo file containing the definition of the column

**Comment by gmsafir** [comment]
sorry, the .geo.txt and .g4s.txt files are not there

**Comment by Lelli-INGENI** [comment]
Hi,

Please find attached both files.

Thanks

LORENZO LELLI
DIRECTEUR

[signature_2557868076]

From: gmsafir ***@***.***>
Reply to: gmsafir/gmsafir ***@***.***>
Date: Tuesday, 14 February 2023 at 07:38
To: gmsafir/gmsafir ***@***.***>
Cc: "Lelli, Lorenzo" ***@***.***>, Author ***@***.***>
Subject: Re: [gmsafir/gmsafir] Zoom Extent in 2D elements (Issue #56)


sorry, the .geo.txt and .g4s.txt files are not there

—
Reply to this email directly, view it on GitHub<https://zendata.urlsand.com/?u=https%3A%2F%2Fgithub.com%2Fgmsafir%2Fgmsafir%2Fissues%2F56%23issuecomment-1429198869&e=c0c93621&h=5e1fbe2c&f=n&p=y>, or unsubscribe<https://zendata.urlsand.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAY6EU2YGJKF5NB3JMETWS2DWXMR5VANCNFSM6AAAAAAUXTRTGA&e=c0c93621&h=0d77f7d0&f=n&p=y>.
You are receiving this because you authored the thread.Message ID: ***@***.***>



##########################################################################################################
################################## GENERAL PROPERTIES ####################################################
##########################################################################################################
Problem Type: Structural 3D
Title1 : Safir_Structural_Analysis
Title2 : Mesh_from_G4S-Mesher
Name of the .IN File : untitled.IN
Consider max displacement : NO
MAX DISPL : 999
PRECISION : 0.001
NG BEAM : 2
Thermal elongation : EPSTH
TIMEPRINT,UPTIMEPRINT : 30,3600
NG SHELLTHICK : 0
NG SOLID : 0
Mode : DYNAMIC PURE NR
Convergence : COMEBACK = {
TIMESTEPMIN : 1e-05
TIMESTEP,UPTIME,TIMESTEPMAX : 1,3600,8
}
outputs : PRINT = {
PRINTDEPL Print the increment of displacement or of temperature : NO
PRINTTMPRT Print the temperature in the beam fibers : NO
PRINTVELAC Print velocity and acceleration : NO
PRINTFHE Print out of balance forces : NO
PRINTREACT Print the reactions : YES
PRINTMN Print the internal forces in beam elements : YES
PRNEIBEAM Print the stiffness EI in beam elements : NO
PRINTSHELL Print the stresses in shell elements : NO
PRNNXSHELL Print the membrane forces in shell elements : NO
PRNMXSHELL Print the bending moments in shell elements : NO
PRNEASHELL Print the membrane stiffness EA in shell elements : NO
PRNEISHELL Print the membrane stiffness EI in shell elements : NO
}


##########################################################################################################
################################## THERMO-MECHANICAL PROPERTIES ###########################################
##########################################################################################################

############### List of MATERIALS already defined (not necessarily assigned to entities/physgroups) ###############

############### List of LAX already defined (not necessarily assigned to entities/physgroups) ###############
Curve - New LAX Definition : laz = {
Check=LAX from local angle, Uncheck=LAX from fix coords : NO
Rotation angle (deg) of Y' around X' : 0
Reverse X' axis : 0
Y'(dx,dy,dz) : 1,0,0
}


############### PROPERTIES assigned to Entities ###############

############### PROPERTIES assigned to Groups ###############
Point - Block Constraint(Physical Point 2) = {
X : F0
Y : F0
Z : F0
Theta-X : NO
Theta-Y : NO
Theta-Z : F0
W : F0
}

Point - Block Constraint(Physical Point 3) = {
X : F0
Y : F0
Z : NO
Theta-X : NO
Theta-Y : NO
Theta-Z : NO
W : F0
}

Curve - Beam Section Local Axes(Physical Curve 4) = {
LAX Name : laz
}

Point - Loads on Node(Physical Point 5) = {
Load Function : FLOAD
X-Force : 0
Y-Force : 0
Z-Force : -100000
X-Moment : 16000
Y-Moment : 16000
Z-Moment : 0
}

Curve - Unif Distr Loads on Beam(Physical Curve 4) = {
Load Function : F1
X Pressure : 0
Y Pressure : 0
Z Pressure : -100
}

Curve - Mass on Beam(Physical Curve 4) = {
Distributed-Beam-Mass : 200
Rotational-Inertia : 1
}




// Gmsh project created on Tue Jan 31 11:49:36 2023
SetFactory("OpenCASCADE");
//+
Point(1) = {0, 0, 0, 0.5};
//+
Point(2) = {0, 0, 3, 0.5};
//+
Line(1) = {1, 2};
//+
Physical Point("BOTTOM_SUPPORT", 2) = {1};
//+
Physical Point("UPPER_SUPPORT", 3) = {2};
//+
Physical Curve("COLUMN", 4) = {1};
//+
Physical Point("CONCENTRATED_LOADS", 5) = {2};

**Comment by gmsafir** [comment]
please update your gmsh API by calling in your command window: 
python.exe install -i https://gmsh.info/python-packages-dev --force-reinstall --no-cache-dir gmsh

and it shall work better

**Comment by Lelli-INGENI** [comment]
Hi,

I’ve the following error :

C:\WINDOWS\system32>python.exe install -i https://gmsh.info/python-packages-dev --force-reinstall --no-cache-dir gmsh

python.exe: can't open file 'C:\\WINDOWS\\system32\\install': [Errno 2] No such file or directory


Is there anything wrong with the syntax of the command line?

Thanks

LORENZO LELLI
DIRECTEUR

***@***.***

De : gmsafir ***@***.***>
Envoyé : mercredi, 15 février 2023 15:47
À : gmsafir/gmsafir ***@***.***>
Cc : Lelli, Lorenzo ***@***.***>; Author ***@***.***>
Objet : Re: [gmsafir/gmsafir] Zoom Extent in 2D elements (Issue #56)


please update your gmsh API by calling in your command window:
python.exe install -i https://gmsh.info/python-packages-dev<https://zendata.urlsand.com/?u=https%3A%2F%2Fgmsh.info%2Fpython-packages-dev&e=c0c93621&h=a75099ff&f=n&p=y> --force-reinstall --no-cache-dir gmsh

and it shall work better

**Comment by gmsafir** [comment]
sorry, there was a typo in the command, here is the correct command:
python.exe -m pip install -i https://gmsh.info/python-packages-dev --force-reinstall --no-cache-dir gmsh

**Comment by Lelli-INGENI** [comment]
Perfect,

Thanks,

I’ll close the issue on the hub adding this command line or are you going to do it?

Regards

LORENZO LELLI
DIRECTEUR

***@***.***

De : gmsafir ***@***.***>
Envoyé : jeudi, 16 février 2023 11:17
À : gmsafir/gmsafir ***@***.***>
Cc : Lelli, Lorenzo ***@***.***>; Author ***@***.***>
Objet : Re: [gmsafir/gmsafir] Zoom Extent in 2D elements (Issue #56)


sorry, there was a typo in the command, here is the correct command:
python.exe -m pip install -i https://gmsh.info/python-packages-dev<https://zendata.urlsand.com/?u=https%3A%2F%2Fgmsh.info%2Fpython-packages-dev&e=c0c93621&h=a75099ff&f=n&p=y> --force-reinstall --no-cache-dir gmsh

**Comment by gmsafir** [comment]
perfect, you can close it

**Comment by Lelli-INGENI** [comment]
Run the following instruction in command prompt:

python.exe -m pip install -i [https://gmsh.info/python-packages-dev] --force-reinstall --no-cache-dir gmsh

**Comment by Lelli-INGENI** [comment]
Run the following instruction in command prompt:

python.exe -m pip install -i [https://gmsh.info/python-packages-dev] --force-reinstall --no-cache-dir gmsh
