### ISSUE TITLE
Comeback & Make.TEM

### ISSUE THREAD

**Issue by berkdemir** [gmsafir/gmsafir#58]
Hi,
I was doing the tutorials of gmsafir, and I noticed that 
`COMEBACK 0.0
MAKE.TEM`
However, when I changed it to
`MAKE.TEM
COMEBACK 0.0`
it works. 
My Safir is old-version, 2019. So, do you understand why it happens?
[Tutorial 2DThermal.g4s.txt](https://github.com/gmsafir/gmsafir/files/10908140/Tutorial.2DThermal.g4s.txt)
[Tutorial 2DThermal.geo.txt](https://github.com/gmsafir/gmsafir/files/10908141/Tutorial.2DThermal.geo.txt)
[Tutorial 2DThermal.geo.opt.txt](https://github.com/gmsafir/gmsafir/files/10908142/Tutorial.2DThermal.geo.opt.txt)

**Comment by gmsafir** [comment]
The order `COMEBACK 0.0
MAKE.TEM` is the correct one for the SAFIR2022 version (please refer to the guide of this version). GmSAFIR is firstly written for SAFIR2022, and might work incorrectly with SAFIR2019.

**Comment by berkdemir** [comment]
Interesting that it fails in earlier versions.
Thanks for confirmation.

**Comment by gmsafir** [comment]
Some precisions after discussion with Jean-Marc:
We assume that you refer to a thermal calculation.
The fact is that the COMEBACK was not possible in thermal calculations in version 2019.
The fact that this version 2019 accepts the sequence,
`MAKE.TEM 
COMEBACK 0.0`
is a pure piece of luck. Nevertheless, the COMEBACK will not be active in this version.

I confirm that, in version 2022, the correct sequence is 
`COMEBACK 1.0
MAKE.TEM`
with, of course, a non-zero number after the command.

**Comment by berkdemir** [comment]
Thanks for following up. Noted. I have to manually remove comeback grom the ini file afterwards in this case. Not very fun, but no problem of course.

Yes, it was the simplest thermal example 1 of gmsafir.

**Comment by berkdemir** [comment]
I presume we should assume that gmsafir is not useable directly for any version before 2022. GmSafir Tutorial 4 in Youtube doesn't have a comeback parameter, but still fails. As I don't have a clear indication of the problem, it's just a guessing game for me.
