### ISSUE TITLE
Trapezoidal loads change when creating new input file

### ISSUE THREAD

**Issue by FlorianP97** [gmsafir/gmsafir#59]
Dear GmSAFIR developers,

I've encountered an issue when using trapezoidal loads. The issue seems to be related to reopening the .geo and .g4s files and creating an input file with a new name.

When defining a geometry and properties and creating an input file immediately after, all works fine. However, when opening the .geo and .g4s files again later to make a new input file, additional lines are added to the 'trapezoidal load' definition in the .g4s files (first time the line 'File for Load Function : y.fct' is added, second time an additional line for pressure is added). The image below shows what the trapezoidal load definition in the .g4s file looks like after I have created 2 new input files with a different name.
![image](https://user-images.githubusercontent.com/114574059/223739818-7999706c-530e-45cc-8b9f-ec0711153de9.png)

Could you take a look at this issue?

Thanks in advance!

Best regards,
Florian
[Test.g4s.txt](https://github.com/gmsafir/gmsafir/files/10921552/Test.g4s.txt)
[Test.geo.txt](https://github.com/gmsafir/gmsafir/files/10921553/Test.geo.txt)

**Comment by gmsafir** [comment]
Download the latest version, it shall fix the problem
