### ISSUE TITLE
Issue torsional analysis

### ISSUE THREAD

**Issue by tgernay** [gmsafir/gmsafir#6]
Hi, I encountered an issue with a torsional analysis.

I created and ran a thermal 2D analysis. Next, I created the torsional input file. I modified the properties and blocked one of the nodes in the model. I created the mesh and the torsional input file, without issue that far. I closed GmSAFIR. I tried running the torsional input file but it did not run. When meshing, GmSAFIR had created two nodes at the same position, and the FIXATION had been applied to node 19 which was not linked to any element. By changing the line in the input file to block node 74 (same coordinates as node 19), it runs. 

However, now GmSAFIR could not open the .geo model anymore. When trying to open the .geo, GmSAFIR closed at once.

I edited the .g4s by removing the lines associated with the torsion constraint. After this edit, I could successfully open the .geo file in GmSAFIR.

So, there seemed to have been an issue when assigning the torsion constraint, and that issue led to the impossibility to reopen the model to modify it in the GUI. It was solvable by identifying that the problem was in the torsion constraint and by editing the file in the text editor. 

I attach the files. Thanks.
[ThermalSteel.geo.txt](https://github.com/gmsafir/gmsafir/files/8406216/ThermalSteel.geo.txt)

[ThermalSteel.g4s.txt](https://github.com/gmsafir/gmsafir/files/8406252/ThermalSteel.g4s.txt)

[ThermalSteel-t.IN.txt](https://github.com/gmsafir/gmsafir/files/8406256/ThermalSteel-t.IN.txt)

**Comment by JMFranssen** [comment]
Thomas,

I once had the same problem. Not so easy to detect.
I think that the problem should be solved by avoiding, from the beginning, to have 2 nodes at the same location. Did you try to apply the command "COHERENCE" in the model, before you apply the BLOCK constrain ? This should remove the "floating" node.
Axelle Dopagne has documented the use of COHERENCE in video 15 on the Youtube Channel: https://www.youtube.com/channel/UC0E-fNxuxk0pQORHy89Lw6g/videos

**Comment by tgernay** [comment]
Hi, no unfortunately applying "coherence" did not help. I had already applied the coherence command in the model after execution of Symmetry. I applied it once more as a check at the end (see script screenshot) but the same issue arises: the fixation gets applied to a node that is floating, so SAFIR torsional does not run.

![image](https://user-images.githubusercontent.com/99494189/161586436-92fd3858-d2df-4e30-a0e5-46f80b37d09d.png)

**Comment by gmsafir** [comment]
Thomas, here is not the full solution to your problem, but a step forward!
The .geo file corresponding to your last screenshot has a problem. When putting Coherence after the first instance of Symmetry, all double points will disappear, so in particular the points 56,57,... so those points cannot be used to build the second Symmetry in your script: when executing your .geo file generates an error message.

Building the second Symmetry correctly is done like this, to be sure to remove all double points :
[ThermalSteel_cor.geo.txt](https://github.com/gmsafir/gmsafir/files/8412339/ThermalSteel_cor.geo.txt)

However, executing then SAFIR2022 with now (after 2 symmetries, each having its coherence) being sure to have a single definition of the torsion point will still generate the same problem ("It is not allowed to make a torsional analysis without a single active node being fixed. Use a BLOCK command to fix the warping function for at least one active node."). But the .IN seems to look fine, no?

By the way, the new version of gmsafir.py, that I just uploaded, solves the problem mentioned by LG Cajot and will also solves your problem of GmSAFIR crashing.

**Comment by tgernay** [comment]
Thanks Bruno for the response. 
Apologies if I am missing it but I do not see the difference with the use of the Coherence in the file with the screenshot versus the _cor.geo.txt attached? Both cases have the Symmetry command followed by the Coherence command, what am I missing?
I downloaded the _cor.geo file and used it to reload the model, add the fixation for the torsion, the mesh, then generate the SAFIR -t.in file. I still have the same outcome: the fixation is applied to 'NODE 19'. 
NODE 19 0.166000 -0.000000
NODE 19 has the same coordinates as node 83.
SAFIR does not run and I get the same error message as you obtained above.

Thanks for the fix in GmSAFIR about the crashing!

**Comment by LGCajot** [comment]
Thanks ;
I confirm that my problem of GmSAFIR crashing has been solved when using the new version of GMSAFIR .
Louis-Guy
