### ISSUE TITLE
How to save mesh for 2-part fall of simulations?

### ISSUE THREAD

**Issue by CarlMBell** [gmsafir/gmsafir#60]
Hello,

I'm doing some gypsum fall-off calculations and i have tried to impose the temperatures of the first calculation with a restartt command in the second calculation calling on the .out file from the first file, but Safir crashes as I start it. My guess is that i don't have node/element alignment between the two calculations as i have removed the gypsum geometry and regenerated a new mesh.

So how do i import the mesh from the first part in GMsafir and make sure my coordinates in my meshes align?

**Comment by gmsafir** [comment]
Please forward your question and files to safir@uliege.be
