### ISSUE TITLE
Gmsafir crashes when implementing a Spring element

### ISSUE THREAD

**Issue by JuanP-Martinez** [gmsafir/gmsafir#62]
Gmsafir crashes when implementing a Spring element within a node. Once 'Add-Update' is clicked, it closes the application. I am using the last version released.
[v3.16.geo.txt](https://github.com/gmsafir/gmsafir/files/11138090/v3.16.geo.txt)
[v3.16.g4s.txt](https://github.com/gmsafir/gmsafir/files/11138092/v3.16.g4s.txt)

**Comment by gmsafir** [comment]
Upload last version, should work now
