### ISSUE TITLE
Crash when I run SAFIR from GmSAFIR 

### ISSUE THREAD

**Issue by KevinFrancazINGENI** [gmsafir/gmsafir#65]
Hello, 

I have a crash problem on my new computer. When I want to "also run SAFIR" from GmSAFIR, the window closes and it doesn't work (there is only the creation of the .IN file). You will find in the attached file all folders and environment variables for :

- Python 3.10.4
- Safir 2022a3
- GmSAFIR

[KFr-GmSAFIR installation.pdf](https://github.com/gmsafir/gmsafir/files/11247958/KFr-GmSAFIR.installation.pdf)

Thanks for your help

Kévin Francaz INGENI

**Comment by KevinFrancazINGENI** [comment]
C:\Users\kevin.francaz>python.exe c:\GmSAFIR\230119\gmsafir.py
['c:\\GmSAFIR\\230119\\gmsafir.py']
Info    : No GEO file found in the directory
listshps= [2]
self.listMats= []
[('ONELAB Context/Shape/Problem Type/Property Type/Temperature Type', 'ONELAB Context/Point Template/Thermal 2D/Block Constraint/-')]
end_lvl= 2
name= ONELAB Context/Point Template/Thermal 2D/Block Constraint/-
[('ONELAB Context/Shape/Problem Type/Property Type/Flux Type', 'ONELAB Context/Curve Template/Thermal 2D/Flux Constraint/-')]
end_lvl= 2
name= ONELAB Context/Curve Template/Thermal 2D/Flux Constraint/-
[('ONELAB Context/Shape/Problem Type/Property Type/Sub-Type', 'ONELAB Context/Surface Template/Thermal 2D/Surface Material/-')]
end_lvl= 2
name= ONELAB Context/Surface Template/Thermal 2D/Surface Material/-
USE_CURVES
[('0Modules/Solver/SAFIR/GENERAL/Problem Type/Convergence', '0Modules/Solver/SAFIR/GENERAL'), ('0Modules/Solver/SAFIR/GENERAL/Problem Type/TEM-TSH', '0Modules/Solver/SAFIR/GENERAL'), ('0Modules/Solver/SAFIR/GENERAL/Problem Type/Type of calculation', '0Modules/Solver/SAFIR/GENERAL')]
-------------------------------------------------------
Version       : 4.12.0-git-1a02bc7b8
License       : GNU General Public License
Build OS      : Windows64-sdk
Build date    : 20230412
Build host    : gmsh.info
Build options : 64Bit ALGLIB[contrib] ANN[contrib] Bamg Blas[petsc] Blossom Cgns DIntegration DomHex Eigen[contrib] Fltk Gmm[contrib] Hxt Jpeg Kbipack Lapack[petsc] MathEx[contrib] Med Mesh Metis[contrib] Mmg Mpeg Netgen NoSocklenT ONELAB ONELABMetamodel OpenCASCADE OpenCASCADE-CAF OpenGL OpenMP OptHom PETSc Parser Plugins Png Post QuadMeshingTools QuadTri Solver TetGen/BR Voro++[contrib] WinslowUntangler Zlib
FLTK version  : 1.4.0
PETSc version : 3.15.0 (real arithmtic)
OCC version   : 7.6.1
MED version   : 4.1.0
Packaged by   : nt authority system
Web site      : https://gmsh.info
Issue tracker : https://gitlab.onelab.info/gmsh/gmsh/issues
-------------------------------------------------------

**Comment by KevinFrancazINGENI** [comment]
GmSAFIR works without crashing, it's only if I click on "Also run SAFIR" and launch the calculation from GmSAFIR that the calculation does not start.

**Comment by gmsafir** [comment]
and no special error message in the cmd window appears after you click on "Also run SAFIR" ?

**Comment by gmsafir** [comment]
and also no message in the cmd window starting with "cmd=..." ?

**Comment by KevinFrancazINGENI** [comment]
[Before clicking on aslo run safir.txt](https://github.com/gmsafir/gmsafir/files/11250360/Before.clicking.on.aslo.run.safir.txt)
[After clicking on aslo run safir.txt](https://github.com/gmsafir/gmsafir/files/11250361/After.clicking.on.aslo.run.safir.txt)

**Comment by gmsafir** [comment]
ok send an email to bruno.guillaume@efectis.com

**Comment by KevinFrancazINGENI** [comment]
ok thank you for your help
