### ISSUE TITLE
Missing Matplotlib in latest version of Python

### ISSUE THREAD

**Issue by RobLWI** [gmsafir/gmsafir#68]
Installing with Python 3.11.3 and the latest gmsafir and gmsh. Tried to start gmsafir.py, but would close straight away.
Seems Matplotlib was missing , had to install it manually, then it was all fine, but could cause confusion for other users.

**Comment by gmsafir** [comment]
thanks for your feedback. We need indeed to update the install guide version

**Comment by RobLWI** [comment]
I can help with that if you like, checking readability,grammar etc, Might be easier for me to check it as I have a bit more distance and can see it with new eyes.

**Comment by gmsafir** [comment]
should be ok now in the new install guide version
