### ISSUE TITLE
FDS-GmSafir

### ISSUE THREAD

**Issue by jeanrova** [gmsafir/gmsafir#69]
Hello,

I write not to report a problem, but to clarify two doubts I have regarding how to use the radiation intensities I obtained on FDS with SAFIR. 

1) I couldn't find the answer online about how I should prepare the FDS output (radiation intensities txt) as input for thermal analysis in GmSafir. Is there a predefined format?

2) After having the txt prepared, should I change the "Flux constraint" of a cross section in Thermal 2D from "HASEMI" to "CFD" or "User-defined"?

Regards

**Comment by gmsafir** [comment]
yes, flux constraint shall be "CFD", and then the preparation of FDS output in dedicated files is not managed by GmSAFIR, but has to follow the specifications found in SAFIR documentation
