### ISSUE TITLE
import math library

### ISSUE THREAD

**Issue by KevinFrancazINGENI** [gmsafir/gmsafir#70]
Hello,

I would like to know if it's possible to import the "math" library in Python to use it while writing scripts via GMSafir? 
Indeed, simply using "import math" in the script doesn't work.

Thanks for your help.

Kévin FRANCAZ INGENI

**Comment by gmsafir** [comment]
"import math", which is required for gmsafir.py, normally comes with your default python install. If not present, you need to install it with your python: python -m pip install math

**Comment by KevinFrancazINGENI** [comment]
I can indeed use the library via Python using the command 'import math', which shows that the library is properly installed. However, my question is about being able to use these functions in the gmsafir script (Edit script). In this case, how should I write the commands?

For example, if I want to calculate a point using the math function:

Point(1) = {math.cos(math.pi), math.sin(math.pi), 0, 1.0};

it doesn't work

**Comment by gmsafir** [comment]
the langage used in the GEO file is not python, it is a simple native langage defined by the Gmsh developers. You can find the built-in functions of this langage here: https://gmsh.info/doc/texinfo/gmsh.html#Built_002din-functions 
I don't see Pi, but probably Acos(-1) is ok

**Comment by KevinFrancazINGENI** [comment]
Hello,

Thank you for your feedback, it's working much better now....

Have a great day!
