### ISSUE TITLE
The models generated in older version of GM Safir crashes upon opening in the newer version

### ISSUE THREAD

**Issue by pkamathHolmes1** [gmsafir/gmsafir#72]
Hello,

I was trying to open 2D and 3D models (*.geo file) that I had generated in an older version of GM Safir on the latest version. The model opens the Gmsh window, however, it crashes in a second or two. 
Wondering if there is a fix for this issue.

Thanks.
PK

**Comment by gmsafir** [comment]
if possible, provide me with your old GEO and G4S, I can see for translation into new format.

**Comment by pkamathHolmes1** [comment]
[3DCONCWITHREBA.zip](https://github.com/gmsafir/gmsafir/files/11596177/3DCONCWITHREBA.zip)
It is a simple 3D model. Please find attached.

**Comment by gmsafir** [comment]
this is the new version of G4S file (GEO file doest not change). To use it, change extension from .g4s.txt to .g4s
[3DCONCWITHREBA.g4s.txt](https://github.com/gmsafir/gmsafir/files/11596262/3DCONCWITHREBA.g4s.txt)

**Comment by gmsafir** [comment]
Ok, let us see for a more verbose way.
Operate in the following sequence :
- Open a windows command prompt (cmd window) ;
- write : python.exe [full_path_directory]\gmsafir.py (=> will open the GmSAFIR window) ;
- then in the GmSAFIR window, go to File/Open... and select your GEO file;
- the GmSAFIR window should crash, and you should see some error and comments in the windows command prompt => send them to me.

**Comment by pkamathHolmes1** [comment]
I followed all the above steps and here's the error on my command prompt.
____________________________________
C:\Users\p******.kamath\Documents\GM Safir\20230420>gmsafir.py
['C:\\Users\\p******.kamath\\Documents\\GM Safir\\20230420\\gmsafir.py']
Info    : No GEO file found in the directory
listshps= [2]
self.listMats= []
end_lvl= 2
name= ONELAB Context/Point Template/Thermal 2D/Block Constraint/-
end_lvl= 2
name= ONELAB Context/Curve Template/Thermal 2D/Flux Constraint/-
end_lvl= 2
name= ONELAB Context/Surface Template/Thermal 2D/Surface Material/-
-------------------------------------------------------
Version       : 4.11.1
License       : GNU General Public License
Build OS      : Windows64-sdk
Build date    : 20221221
Build host    : gmsh.info
Build options : 64Bit ALGLIB[contrib] ANN[contrib] Bamg Blas[petsc] Blossom Cgns DIntegration DomHex Eigen[contrib] Fltk Gmm[contrib] Hxt Jpeg Kbipack Lapack[petsc] MathEx[contrib] Med Mesh Metis[contrib] Mmg Mpeg Netgen NoSocklenT ONELAB ONELABMetamodel OpenCASCADE OpenCASCADE-CAF OpenGL OpenMP OptHom PETSc Parser Plugins Png Post QuadMeshingTools QuadTri Solver TetGen/BR Voro++[contrib] WinslowUntangler Zlib
FLTK version  : 1.4.0
PETSc version : 3.15.0 (real arithmtic)
OCC version   : 7.6.1
MED version   : 4.1.0
Packaged by   : nt authority system
Web site      : https://gmsh.info
Issue tracker : https://gitlab.onelab.info/gmsh/gmsh/issues
-------------------------------------------------------
Info    : Reading 'C:/SAFIR/4_TRIALS/GMSafir/Block3D (mod to open in new GMSafir)/3DCONCWITHREBA.geo'...
Info    : Done reading 'C:/SAFIR/4_TRIALS/GMSafir/Block3D (mod to open in new GMSafir)/3DCONCWITHREBA.geo'
Info    : Reading 'C:/SAFIR/4_TRIALS/GMSafir/Block3D (mod to open in new GMSafir)/3DCONCWITHREBA.geo'...
Info    : Done reading 'C:/SAFIR/4_TRIALS/GMSafir/Block3D (mod to open in new GMSafir)/3DCONCWITHREBA.geo'
inside permuteDB: ivl= ['Safir_Thermal_3D_Analysis']
inside permuteDB: tmpk0["props"][idx]= {'name': 'Title1', 'type': 'string', 'values': ['Safir_Thermal_3D_Analysis']}
inside permuteDB: tmpk0["props"][idx]= {'name': 'Title1', 'type': 'string', 'values': ['Safir_Thermal_3D_Analysis']}
inside permuteDB: ivl= ['Mesh_from_G4S-Mesher']
inside permuteDB: tmpk0["props"][idx]= {'name': 'Title2', 'type': 'string', 'values': ['Mesh_from_G4S-Mesher']}
inside permuteDB: tmpk0["props"][idx]= {'name': 'Title2', 'type': 'string', 'values': ['Mesh_from_G4S-Mesher']}
inside permuteDB: ivl= ['0.001']
inside permuteDB: tmpk0["props"][idx]= {'name': 'PRECISION', 'type': 'number', 'values': [0.001], 'min': 0, 'max': 0.1, 'step': 0.001}
inside permuteDB: tmpk0["props"][idx]= {'name': 'PRECISION', 'type': 'number', 'values': [0.001], 'min': 0, 'max': 0.1, 'step': 0.001}
inside permuteDB: ivl= ['0.9']
inside permuteDB: tmpk0["props"][idx]= {'name': 'TETA', 'type': 'number', 'values': [0.9], 'min': 0, 'max': 1, 'step': 0.1}
inside permuteDB: tmpk0["props"][idx]= {'name': 'TETA', 'type': 'number', 'values': [0.9], 'min': 0, 'max': 1, 'step': 0.1}
inside permuteDB: ivl= ['20']
inside permuteDB: tmpk0["props"][idx]= {'name': 'TINITIAL', 'type': 'number', 'values': [20], 'min': 0, 'max': 1, 'step': 0.1}
inside permuteDB: tmpk0["props"][idx]= {'name': 'TINITIAL', 'type': 'number', 'values': [20], 'min': 0, 'max': 1, 'step': 0.1}
inside permuteDB: ivl= ['30,3600']
inside permuteDB: tmpk0["props"][idx]= {'name': 'TIMEPRINT,UPTIMEPRINT', 'type': 'string', 'values': ['30,3600']}
inside permuteDB: tmpk0["props"][idx]= {'name': 'TIMEPRINT,UPTIMEPRINT', 'type': 'string', 'values': ['30,3600']}
inside permuteDB: ivl= ['0']
inside permuteDB: tmpk0["props"][idx]= {'name': 'Use matrix diag (DIAG CAPA)', 'type': 'number', 'values': [0], 'choices': [0, 1], 'valueLabels': {'NO': 0, 'YES': 1}, 'visible': True}
Traceback (most recent call last):
  File "C:\Users\p******.kamath\Documents\GM Safir\20230420\gmsafir.py", line 8998, in <module>
    while myapp.eventLoop():
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\p******.kamath\Documents\GM Safir\20230420\gmsafir.py", line 6294, in eventLoop
    self.getG4sJson(self.g4sfile) # if existing DB in input directory
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p******.kamath\Documents\GM Safir\20230420\gmsafir.py", line 681, in getG4sJson
    tmp0=changeSafirDBKeyAndProp(iprop,ival)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
________________________________________________

**Comment by gmsafir** [comment]
ok now it is clear, I had introduced an erroneous element in the G4S file. Retry with this new one
[3DCONCWITHREBA.g4s.txt](https://github.com/gmsafir/gmsafir/files/11605240/3DCONCWITHREBA.g4s.txt)

**Comment by pkamathHolmes1** [comment]
Perfect! works now. So any G4S generated using old GM Safir needs a fix before opening in the new version of GM Safir? What would be the best way to do it?

**Comment by gmsafir** [comment]
no, only my conversion went wrong, the normal generation of the new version of G4S file with the recent versions of GmSAFIR, shall work properly. Tell me if something wrong happens
