### ISSUE TITLE
Doubt with "Transform-Translate"

### ISSUE THREAD

**Issue by Altorcas** [gmsafir/gmsafir#73]
Hello

To start with, I would like to say hello to everyone.

I am modelling a 3D structure, and I'm using the command "transform-translate"  cause the structure is repetitive. We are trying to replicate/translate not only the geometry rather than the properties (beams loads, mass, beam section type, relaxations...).

It seems that it may only works for the geometry but not for the properties as stated above. Is there any way to copy the these properties besides the geometry?

Any feedback in this regard would be highly appreciated.

Thank you so much.
Regards.

**Comment by gmsafir** [comment]
Transform-translate indeed is only for replication of geometry. Replication of thermal-mechnical properties is essentially by using "physical groups", where a "container" of same property can extend the properties to new elements by adding the new elements in this container : ex. you define a new "Physical Curve", for which beam load has given properties, and you add in it the Curves 1,2, 5,10,...
