### ISSUE TITLE
Default WoodEC5 properties versus user defined values

### ISSUE THREAD

**Issue by ankitDBI** [gmsafir/gmsafir#74]
This is more of a SAFIR question than a GmSAFIR issue but I thought I should share here anyways. I'm trying to use modified thermal properties as per the latest Eurocode 5 for timber. However, I wanted to verify the default values first before proceeding. I specified thermal properties as per Eurocode 5 but am getting different results from the default 'Wood EC5' material. Would it be possible to know what are the exact thermal property values that are being specified as per the 'Wood EC5' material? I've attached the respective input files labeled 'Timber2dSensitivity490-12pcEC2004' with a user defined material and 'Timber2dSensitivity490-12pcDefault1' with default SAFIR properties (WoodEC5).
![image](https://github.com/gmsafir/gmsafir/assets/136335097/177bbbd7-c9ac-40a8-8213-8f58e1862527)
[Timber2dSensitivity490-12pcDefault1.txt](https://github.com/gmsafir/gmsafir/files/11733868/Timber2dSensitivity490-12pcDefault1.txt)
[Timber2dSensitivity490-12pcEC2004.txt](https://github.com/gmsafir/gmsafir/files/11733869/Timber2dSensitivity490-12pcEC2004.txt)

**Comment by JMFranssen** [comment]
This question is Indeed directly related to SAFIR and has nothing to do with GmSAFIR.
You can ask this kind of question to safir@uliege.be.
You could thus receive a faster answer (if you sign your message).

Nevertheless, the differences between your two models come from the fact that:
1) You gave an emissivity of 0,8 for the material WOODEC5 and of 0,7 for the material USER1
2) You introduced in the USER1 material the increase of specific capacity that is given in EC5 from 99 to 120 degrees, whereas this "rectangle" that extends up to 15,5 KJ/.kgK as can be seen on Figure B2, is already taken into account explicitly by the evaporation of moisture in the USER1 material. Evaporation of moisture is thus accounted for twice in your USER1 material. 

Note that the most recent versions of SAFIR have a new timber material "WOOD2020" which corresponds to prEN 1995-1-2: 2020. There are slight differences with the version of EN 1995-1-2: 2004

Regards

J-M Franssen
