### ISSUE TITLE
Unable to refine mesh in GmSAFIR without introducing clockwise element numbers or negative Jacobian

### ISSUE THREAD

**Issue by ankitDBI** [gmsafir/gmsafir#75]
I face an error whenever I try to refine the mesh by splitting in the attached model. The generated input file runs when the mesh is fairly coarse (no splitting), but stops running because of clockwise element numbering (or negative Jacobian) when the mesh is refined. Any advice on how to possibly resolve the issue would be greatly appreciated. The .geo and .g4s files are attached as text files for reference.
[IFB-TypeA.GEO.txt](https://github.com/gmsafir/gmsafir/files/11746521/IFB-TypeA.GEO.txt)
[IFB-TypeA.G4S.txt](https://github.com/gmsafir/gmsafir/files/11746522/IFB-TypeA.G4S.txt)

**Comment by gmsafir** [comment]
indeed, that is a weird situation, that can be monitored with double clicking, and selecting "All mesh options..."/Visibility, and putting a couple of values like (50,0) to "Normals and tangents".
In no splitting case, all normals are ok:
![no_splitting](https://github.com/gmsafir/gmsafir/assets/99477211/7b5de7f2-86cc-4dc7-bb3b-59a8676e33e8)
Also when refining only once:
![refine_once](https://github.com/gmsafir/gmsafir/assets/99477211/db8ab9eb-77f8-4f90-b806-c353f81faba0)
But when refining twice, 2 normals suddendly become wrong direction:
![refine_twice](https://github.com/gmsafir/gmsafir/assets/99477211/8f647e7c-974b-483c-8c90-a609f0a093b6)

There are 2 levels of answers, one is quick and dirty and the other is more complete.

The quick and dirty is a direct solution wihtout explanation, that will work I guess. After getting the bad normals, if you reclick on Mesh/2D, the normals are all ok again. If refining once, again all normals are ok.
![redo_2Dmesh_and_refine](https://github.com/gmsafir/gmsafir/assets/99477211/ae93a71d-4e25-4def-8ce3-9d78069d936a)

The complete answer with full explanation will require more time. I will let you know when solved
