### ISSUE TITLE
How do I split and merge curves?

### ISSUE THREAD

**Issue by Altorcas** [gmsafir/gmsafir#76]
Good afternoon,
I have a simple 3D structural model with beam elements, as you can see in the next picture. 

![ExampleStructure_SplitLine](https://github.com/gmsafir/gmsafir/assets/135019498/dac50637-8afe-4014-8173-d5fa93850cd6)

I would like to introduce a point on the beam highlighted in red to split the element into two (notice that the point is located at 0.2·L from one of the columns). I use the ‘split curve' command in the editor, but I receive the following error message: ‘_split curve not available with OpenCASCADE geometry kermel_’

Am I doing it correctly? In simple structural models like this, I can remove the beam and introduce this point, but in more complex models, it wouldn't be as straightforward.

On the other hand, what if I have the following example:

![ExampleStructure_SplitLine2](https://github.com/gmsafir/gmsafir/assets/135019498/f183a90c-40ab-4ea5-91ac-3ab246d981fc)

Is there any command to merge the curve defined by lines 8, 9 and 10 into only one?

Thank you so much!
Regards.

**Comment by gmsafir** [comment]
@Altorcas, please upload here the 2 geofiles, for each of your 2 questions

**Comment by gmsafir** [comment]
(change .geo in .geo.txt before upload)

**Comment by Altorcas** [comment]
Good morning,

Attached to this message you will see both .geo uploaded as .txt. 
Both files have only the geometry in which we would like to know how to split/merge curves.

Thank you so much.


[Question1_split.txt](https://github.com/gmsafir/gmsafir/files/11946936/Question1_split.txt)
[Question2_merge.txt](https://github.com/gmsafir/gmsafir/files/11946937/Question2_merge.txt)

**Comment by Altorcas** [comment]
Good morning!

Thank you so much for your answer, I have been trying it, and both operations work perfectly!

On the other hand, I would like to know if splitting curves with no points defined on them is possible, eg: I want to split curve 7 into 3 different curves. Besides the "split curve" command, which I don't think it's appropriate for this purpose, I haven't found anything related to this in the manual. 

Any help regarding this question will be highly appreciated.

Thank you so much.
Regards.

**Comment by gmsafir** [comment]
What do you mean by "splitting curve 7 into 3 different curves"? Do you mean with 3 equal  lengths curves?

**Comment by Altorcas** [comment]
> What do you mean by "splitting curve 7 into 3 different curves"? Do you mean with 3 equal lengths curves?

Good morning!

Yes, split the curve into 3 (in this case) or "n" equal length curves.

Thank you.

**Comment by gmsafir** [comment]
No, there is no "equal-length automatic fragmentation" in GMSH. If you want N equal-length subcurves, you need to place your (N-1) equal-distanced points and use (N-1) times the BooleanFragments operator.
