### ISSUE TITLE
Using 'Recombine' function in batch mode

### ISSUE THREAD

**Issue by FlorianP97** [gmsafir/gmsafir#78]
Hi,

I was wondering whether it is possible to use the mesh functions of gmsafir such as 'recombine' and 'refine by splitting' when using the batch mode without opening gmsafir.

Thanks in advance!

**Comment by gmsafir** [comment]
Yes
For batch mode, please refer to this previous Issue:
https://github.com/gmsafir/gmsafir/issues/46

**Comment by FlorianP97** [comment]
Yes, that allows me to use the batch mode. However, I wondered how we can use the specific meshing functions from gmsafir within the batch mode. Should we add something to the syntax "python.exe [full_path]/gmsafir.py [full_path_directory] -nopopup"?

**Comment by gmsafir** [comment]
ok the solution is then to include the meshing, then recombine and 2x refine in the geofile as in the attached file:
[IFB-TypeA.geo.txt](https://github.com/gmsafir/gmsafir/files/11929033/IFB-TypeA.geo.txt)
