### ISSUE TITLE
Reload of g4s file

### ISSUE THREAD

**Issue by Kongzhu79** [gmsafir/gmsafir#79]
I have a request. I would like it to be possible to edit and reload the scripting made in the g4s file in a similar manner as for the geo file. Sometimes I need to check something in the g4s file and then it is easier to change directly in the file rather than going back to gmSafir. If this is done, I need to restart gmSafir in order for the changes to take place.

**Comment by gmsafir** [comment]
Once you have edited your g4sfile, simply click on the "VIEW/Reload properties" button, it should work.

**Comment by Kongzhu79** [comment]
Then I am sorry for bothering you. Will do.
