### ISSUE TITLE
Error: Geo File has not yet been created

### ISSUE THREAD

**Issue by marpitt** [gmsafir/gmsafir#8]
When i try to add properties I get the error mentioned above even though the file is a .geo. 
When i start a new project there is only a .geo and not a .g4s. Could that be the source of the error?

**Comment by gmsafir** [comment]
Hi, I need more precisions.

Do you have this entire message that does appear as a red warning at the bottom of the GUI : "The GEO file has not yet been created => these first changes (problem type...)  will not be taken into account until the GEO file is created" ?
When you open the GUI, do you load the GEO by "File/Open..." or generate a new file by "File/New..." ?
Just after doing so, do you have no red warning message in the bottom page, before opening the properties menu ?

If you answered "Yes" to the 3 above questions, then I have no clue of the problem: in that case, can you please upload your GEO file here ? (or a simplified version of it, that would generate the same problem). Remember to rename it by adding ".txt" at the end of the filename.

**Comment by tgernay** [comment]
Hi, I have the same problem, with the newest version of GmSAFIR (downloaded on April 4, 2022). I believe this might be a new problem that was not present in the former version.

**Comment by marpitt** [comment]
I tried new projects (File/New) and and to load current projects (File/Open). I can create the geometrie but as soon as i try to create some physical groups i get exactly the red error in at the bottom of the GUI you mentioned in your text. After loading or creating a new project i don´t have the error message. I can attach my File but i have the error message with any File, even if i simply try two points with one line.

**Comment by gmsafir** [comment]
please, try again with the new version (I just updated it), and tell me if problem is solved

**Comment by tgernay** [comment]
Hi Bruno, the problem is solved. Thanks!

**Comment by marpitt** [comment]
Yes the problem is solved, thank you for the fast help!
