### ISSUE TITLE
Spring

### ISSUE THREAD

**Issue by luisalvesqueiroz** [gmsafir/gmsafir#80]
Could you clarify the input parameters for spring? especially area of influence and superior and inferior limits of the force

**Comment by gmsafir** [comment]
Same parameters as in the technical document of "SAFIR Mechanical Simulations". If more doubt, ask your question at SAFIR hotline : [SAFIR@uliege.be](mailto:SAFIR@uliege.be)

**Comment by luisalvesqueiroz** [comment]
Yes, but there is no details. I will email them. Thank you.
