### ISSUE TITLE
Safir and spring element error

### ISSUE THREAD

**Issue by luisalvesqueiroz** [gmsafir/gmsafir#81]
How can I deal with this error? it looks like safir doesnt recognize spring elements from gmsafir
SAFIR version 2022.c.1 (25/06/2023) is running.
  SAFIR is allocating memory
 ERROR from SAFIR in subr. DIMARRAY.
 "NSPRING   " is not a valid element type.
 PLEASE MOFIFY THE .IN FILE.

**Comment by gmsafir** [comment]
Please upload a set of .GEO and .G4S files

**Comment by luisalvesqueiroz** [comment]
[archtwosprings.zip](https://github.com/gmsafir/gmsafir/files/12251589/archtwosprings.zip)
Here they are.
