### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by miguelmaso** [gmsafir/gmsafir#86]
Dear all,

The readme states that

> It is free and open-source

however, there is no license file.

Right now, my team is using SAFIR+GiD with the corresponding licenses and we want to move from GiD to GMSafir. To do so, we would feel more confortable if a license file confirmed it. Furthermore, the open-source license will help there be more collaborative participation.

There are several license templates (BSD, MIT, CC...) but I think that its better to leave the initiative to the project owners.

Of course, I have experience with other open source projects, if I can help in any way, do not hesitate to contact me.

**Comment by gmsafir** [comment]
ok, here it is, thanks for raising this issue
