### ISSUE TITLE
Cannot open gmSafir

### ISSUE THREAD

**Issue by Kongzhu79** [gmsafir/gmsafir#87]
Although gmSafir has previously worked on my computer, the most recent attempt failed. I got this error message.

![bild](https://github.com/gmsafir/gmsafir/assets/71386339/2a81d304-fdfd-4691-853a-1d4698238c85)

Since last time, I have updated gmSafir to the latest version and also gotten python 3.12 installed on my computer. Don't know if this makes any difference.

**Comment by gmsafir** [comment]
please provide one set of GEO+G4S files to reproduce  the error on our side

**Comment by Kongzhu79** [comment]
The error occurs when I try to open gmSafir, before I even get to any of the open-file stuff.

**Comment by Kongzhu79** [comment]
It seems to be a Python 3.12 issue. I tried to launch the code from my IDE with Python 3.11 as the designated compiler which worked. After the installation of 3.12 it seems to have become my default python compiler. Don't know if it is best to stick to 3.11 and be clear with it or upgrade to 3.12 . That, I leave to you.

**Comment by Kongzhu79** [comment]
Thank you. I had to add "pip install matplotlib" as well to make it work. Hopefully, all should be fine now.
