### ISSUE TITLE
Mesh parameters in batch mode

### ISSUE THREAD

**Issue by FlorianP97** [gmsafir/gmsafir#88]
Hi GmSAFIR developers,

In gmsh, it is possible to modify the mesh parameters (specifically element size factor) in the options>mesh>general menu. Is it possible to use this functionality in the 'batch' mode and if yes, which statement should be used and in which file?

Thanks in advance!

Best regards,
Florian

**Comment by gmsafir** [comment]
Sure. You can use the Mesh.MeshSizeFactor command in your GEO file.
Look at to deal with it here : https://gmsh.info/doc/texinfo/gmsh.html#Overview-of-Gmsh

**Comment by FlorianP97** [comment]
This is a great reference, thanks!
