### ISSUE TITLE
Script error when creating themal 2D inmput file containing stainless steel material

### ISSUE THREAD

**Issue by OBeckmann** [gmsafir/gmsafir#89]
Hi, I just wanted to let you know that wehn creating a thermal 2D cross section input file, for some reason, GMSafir will add an additional material line although only one material was defined:
![image](https://github.com/gmsafir/gmsafir/assets/119671602/b199aa30-cd30-4254-abba-c1bea1073e0d)
The name of the extra material is one of the mechanical material names (SLS1.4301).
Additionally,  the material type "STAINLESS STEELS" written in the input file is not recognized due to the space in the name (don't know what the name should be correctly)

BR,
Oliver

[CS10mm2.zip](https://github.com/gmsafir/gmsafir/files/13599056/CS10mm2.zip)

**Comment by gmsafir** [comment]
I just uploaded a new version. Previous version has introduced a bg in your G4S file, please regenerate it before creating the IN file

**Comment by OBeckmann** [comment]
Hi, thanks for adjusting.
Unfortunately, GmSafir will not start with the new version file. A command window quickly pops up but nothing else is happening. Do you have an idea what might be causing this ?
BR, Oliver

**Comment by gmsafir** [comment]
matplotlib is now indeed required, which was not the case earlier. Did you regenerate from scratch the G4S file (and not reuse it), before generating the .IN file?

**Comment by OBeckmann** [comment]
Hi, I recreated the whole model from the scratch.
