### ISSUE TITLE
COMEBACK in Structural 2D

### ISSUE THREAD

**Issue by tgernay** [gmsafir/gmsafir#9]
Hi, I think the COMEBACK line in Structural 2D Problem Type is not written by GmSAFIR at the right location for SAFIR2022a0.
In the example below (Structural 2D), the COMEBACK line gets written after NDOFMAX and before DYNAMIC PURE_NR.
It should be written right before NMAT.
SERIES 7: INCLINED SUPPORTS
SERIES 8: CONVERGENCE STRATEGY
SERIES 9: QUANTITY OF MATERIALS

[2DFrame.geo.txt](https://github.com/gmsafir/gmsafir/files/8423123/2DFrame.geo.txt)
[2DFrame.g4s.txt](https://github.com/gmsafir/gmsafir/files/8423125/2DFrame.g4s.txt)
,

**Comment by gmsafir** [comment]
I changed the place
