### ISSUE TITLE
Parametric geometry input

### ISSUE THREAD

**Issue by Pbieghs** [gmsafir/gmsafir#91]
Hi, 
A collegae of mine wants to use GMSafir for fire calculations.
In order to do that he needs to be able to draw a lot of different steel profiles correctly. 
In orde to save time I would like to automate the drawing of these profiles by just using the profile type (ex: HEA120) as input and the program should return the proper geometry.
 
I managed to write a python code that, when running, returns the correct points, lines and surfaces as needed.
 
![image](https://github.com/gmsafir/gmsafir/assets/147591494/c2600c6e-3bf1-494f-a18e-1fb405b366d8)

but how do I get this information into gmsafir for proper meshing and other safir data?

I can't run both gmsafir and my code at the same time
The geometry is saved from the python code is a .msh file, but when opening this in gmsafir it only shows points, which I can't use to further make a .geo file.

mashing my code and the gmsafir.py code together isn't really working. (I'm probably doing it all wrong)

Another idea was to rewrite the code within the .geo file,
I Tried using DefineConstant for the different parameters, but once you try to change something the menu options disappears and no changes were made. 
The goal of inputting a profile also relies on reading a dictionary with the corresponding parameters, but I'm struggeling with getting a dictionary in the code to properly read all this data.

I tried adding a dictionary to the source code of gmsafir, but I'm getting stuck at the addition of parameters in the menu. if I try to change anything I get an errormessage that the .g4s file is not recognized.
After that I still have to figure out how I can read this parameter in the menu. 

Is there a proper way to do this kind of thing? 
Am I missing something improtant, am I going about it the wrong way?
I would love to get some imput because I'm really stuck.

**Comment by gmsafir** [comment]
You can easily create a parameterized version of your HEA object, like in the Gmsh tutorial 1 (see here: https://gmsh.info/doc/texinfo/gmsh.html and look for t1.geo). Then the head of your GEO file would contain different parameters: (length=..., size1=..., ) for which you could easily attribute different sets of values via a small python script
