### ISSUE TITLE
Problems with assigning voids

### ISSUE THREAD

**Issue by l-rutkauskas** [gmsafir/gmsafir#93]
Hi,

I've been struggling with adding voids with GM. SAFIR requires voids to be described in the counter clockwise direction. However, GMSH will only create the input file with void elements as counter clockwise if the void boundary line normals in the model are also counter clockwise. 

For more complicated models it is very difficult to keep all void boundary lines directed in counter clockwise, especially if there is some geometry manipulation done in GM.

Is there any workaround to this issue?

Thank you,
Lukas

![image](https://github.com/gmsafir/gmsafir/assets/125242769/f2df89bd-363b-4695-b5c7-a8d2ab47202a)

**Comment by l-rutkauskas** [comment]
[void_test.IN.txt](https://github.com/gmsafir/gmsafir/files/14033347/void_test.IN.txt)
[void_test.g4s.txt](https://github.com/gmsafir/gmsafir/files/14033348/void_test.g4s.txt)
[void_test.geo.txt](https://github.com/gmsafir/gmsafir/files/14033349/void_test.geo.txt)

**Comment by gmsafir** [comment]
Hi,

An old SAFIR will require that all lines (Curves in GmSAFIR) constitutive of the VOID are oriented so as to define a VOID that is anticlockwise, while a recent version of SAFIR will not have this requirement. Change the orientation of each line not conform to this constraint.
Independently the GmSAFIR Surfaces supporting the mesh elements need to be defined for SAFIR in anticlockwise orientation. But contrarily to the VOID in GmSAFIR, the orientation of one Surface does not required that all constitutive lines have a correct orientation : the orientation of the Surface is defined by the orientation of the first line of the group of lines constitutive of the Surface. So for each Surface adjacent to the VOID, you can select any line that belongs exclusively to the Surface (and not to the adjacent VOID) and return its orientation and build the Surface with this line in first position.
