### ISSUE TITLE
Gmsafir .IN file incomplete shell model 

### ISSUE THREAD

**Issue by binvernizzi** [gmsafir/gmsafir#96]
I have to develop a 3D structural analysis of a shell model. 
I have the .TSH file with the 2D thermal analysis, I created the shell model (.geo and .g4s file). When I try to create the .IN file gmsafir closes and the .IN file results uncomplete. 

I attached the files to this link
SHELL
Password: CH2p49CPGyuZ
https://jensenhughes.egnyte.com/fl/KtPKROxULc

**Comment by gmsafir** [comment]
the problem originates from the fact that, when you open your GEO file in GmSAFIR, you see a read error message in the log window, saying that "LAX Name lax001 is not in the current list. Please define it first before allocating". Indeed, in your G4S file, lax001 has no definition. Find in the Curve menus the item "New LAX definition" and define it with name lax001
