### ISSUE TITLE
No Such File Error During GMSH Installation

### ISSUE THREAD

**Issue by aboin4** [gmsafir/gmsafir#97]
Hello, I am trying to import gmsh into Python according to step 4 of the installation guide and I keep receiving this error. I have tried a couple different directories to house Python but those attempts still came back with this error - any ideas on how to fix this?

![Screenshot 2024-03-25 162026](https://github.com/gmsafir/gmsafir/assets/164943140/92b968cf-b295-42bc-b2cc-91e04e4a651a)

**Comment by kowalskiw** [comment]
Hi, it seems similar to the issue from this thread: https://stackoverflow.com/questions/50591810/ec2-python-cant-open-file-m-errno-2-no-such-file-or-directory

Have you tried typing the `python -m pip` command manually (not copying it)?
